### ISSUE TITLE
Avoid requirement to register DelegatingHandler manually

### ISSUE THREAD

**Issue by stevejgordon** [aspnet/HttpClientFactory#104]
Would it be reasonable to update AddHttpMessageHandler<THandler> to include a line to first register the handler with DI? This avoids the need for it to be manually registered before it's added. It feels like one of those things that may be easy to forget to do.

Something like this?

```
public static IHttpClientBuilder AddHttpMessageHandler<THandler>(this IHttpClientBuilder builder)
	where THandler : DelegatingHandler
{
	if (builder == null)
	{
		throw new ArgumentNullException(nameof(builder));
	}

	builder.Services.TryAddTransient(typeof(THandler));

	builder.Services.AddTransient<IConfigureOptions<HttpClientFactoryOptions>>(services =>
	{
		return new ConfigureNamedOptions<HttpClientFactoryOptions>(builder.Name, (options) =>
		{
			options.HttpMessageHandlerBuilderActions.Add(b => b.AdditionalHandlers.Add(services.GetRequiredService<THandler>()));
		});
	});

	return builder;
}
```

If it's being added to multiple clients TryAddTransient should avoid any negative outcomes.

**Comment by martincostello** [comment]
Especially if it’s `TryAdd...` this would make things much neater for the simple cases where you can rely on DI to make the type for you without a factory delegate.

**Comment by mkArtakMSFT** [comment]
Hi @stevejgordon.
We considered doing this but didn't, because we weren't sure how broadly applicable it will be.
There are plenty of special cases of how you interact with DI and we didn't want to build something that solves part of the problem.
