### ISSUE TITLE
CachePolicy with default cache key strategy results in the cache never been called

### ISSUE THREAD

**Issue by ymor** [aspnet/HttpClientFactory#106]
The [DefaultCacheKeyStrategy ](https://github.com/App-vNext/Polly/blob/5.8.0%2B8-(Build-554)/src/Polly.Shared/Caching/DefaultCacheKeyStrategy.cs) uses the ExecutionKey from the Polly [Context](https://github.com/App-vNext/Polly/blob/5.8.0%2B8-(Build-554)/src/Polly.Shared/Context.cs).  However this seems to never get set and so the Polly [CacheEngineAsync](https://github.com/App-vNext/Polly/blob/5.8.0%2B8-(Build-554)/src/Polly.Shared/Caching/CacheEngineAsync.cs#L25) never tries the cache.  

There doesn't seem to be enough information on the Context to even create a custom CacheKeyStrategy.  Is it possible to add some of the request information onto the Context?

**Comment by reisenberger** [comment]
@ymor Before placing the call through HttpClient, you can use [this extension method](https://github.com/aspnet/HttpClientFactory/blob/f0e32f2b8caa3667aba3938a5a21a039295edb71/src/Microsoft.Extensions.Http.Polly/HttpRequestMessageExtensions.cs#L48) on `HttpRequestMessage` to set the `Polly.Context` to use with the request.  

    request.SetPolicyExecutionContext(new Polly.Context("CacheKeyToUseWithThisRequest"));

That example assumes your CachePolicy is using the [default cache key strategy](https://github.com/App-vNext/Polly/wiki/Cache#default-cachekeystrategy-if-none-specified).  If you use a [custom cache key strategy](https://github.com/App-vNext/Polly/wiki/Cache#cachekeystrategy-optional) you can vary the `Context` you pass to `request.SetPolicyExecutionContext(...);` to fit your custom strategy.

@rynowak @stevejgordon  We need to get this in the documentation, whether [Polly's](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory) (I'll draft something there) or the [official aspnet/docs version](https://github.com/aspnet/Docs/pull/5483).

**Comment by reisenberger** [comment]
I have added some initial notes [here](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-cachepolicy) in Polly's doco around IHttpClientFactory and Polly CachePolicy.  The doco notes some considerations around caching at the low level of the raw `HttpResponseMessage`.

**Comment by ymor** [comment]
Thanks, those considerations were things i hadn't thought about!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
