### ISSUE TITLE
Production ready version that works with .NET core 2.0

### ISSUE THREAD

**Issue by VenkateshSrini** [aspnet/HttpClientFactory#107]
Hi,
I see that this project uses some in preview version of dependencies. Could you please provide a production ready version of this library that works with .NET core 2.0?

**Comment by rynowak** [comment]
We have no plans to do this. We rely on new features that were added in 2.1 in options for the configuration experience. 

If this is an absolute requirement for you, I recommend building the repo yourself - you could prune out the code paths that use those new APIs
