### ISSUE TITLE
Have we time to re-point HttpClientFactory at a new (signed) Polly v6.0.0 before RTM?

### ISSUE THREAD

**Issue by reisenberger** [aspnet/HttpClientFactory#108]
#105 reached the conclusion Polly should release only as a single, strong-named version to avoid sn / non-sn conflicts in the OSS ecosystem driven by the ASPNET Core2.1/Polly integration.

@damianedwards @glennc @rynowak /cc @joelhulen : Have we time before ASPNET Core 2.1 RTMs, to implement this and re-point HttpClientFactory (Microsoft.Extensions.Http.Polly) at the new Polly v6.0.0 ? 

At the Polly end it is only a package/build change (no new code; delete some already-deprecated code), but we would need few days* to get it right and ripple across related Polly packages (six total?).

---

Most other scenarios sound painful ...

If Microsoft.Extensions.Http.Polly RTMs referencing Polly-Signed v5.9.0, and Polly shortly thereafter were to deprecate Polly-Signed and bump to Polly v6.0.0 as the single (signed) Polly package, we create more of exactly the pain we are trying to avoid.  Microsoft.Extensions.Http.Polly would hold users to including Polly-Signed, whereas other projects (or the desire to adopt new features) would drive users to the new Polly >=v6.0.0 package. But the two would clash at compilation time [as prev highlighted](https://github.com/BrighterCommand/Brighter/issues/286).

In fact if Microsoft.Extensions.Http.Polly had to RTM referencing Polly-Signed v5.9.0, we may likely be better waiting on packaging changes to Polly until Microsoft.Extensions.Http.Polly could be re-released referencing Polly >=v6.0.0.  If there were several months to that [EDIT: _if_ needing to wait for eg Core 2.2], some Polly users/projects would hit the pain of both packages having a strong presence in the market in that period.

_Also_: Would changing Microsoft.Extensions.Http.Polly from referencing Polly-Signed v5.9.0 to Polly v6.0.0 _after_ release, be considered (from semver perspective) a breaking change to Microsoft.Extensions.Http.Polly that affects release numbering, or not? 

... all seems to point to ideally doing this before RTM?

**EDIT**: if sensitive to discuss the ASPNET Core 2.1 RTM date via this forum , @rynowak and @glennc do have direct email for myself and @joelhulen

**Comment by rynowak** [comment]
I agree this would cause a lot of pain given the plans. Let me talk to folks on our side.

**Comment by rynowak** [comment]
@reisenberger @joelhulen - it's very likely that we'll get approval to do this.

**Comment by joelhulen** [comment]
@rynowak Great! Thank you :) We're working on this now. Please stay tuned...

**Comment by iancooper** [comment]
@reisenberger Should we depend on this, or wait for a non-alpha package i.e. what version are you likely to go with for 2.1 RTM?

**Comment by reisenberger** [comment]
@iancooper Polly v6.0.1 (rtm, non-pre-release) should publish to nuget in the next 24 hours.  Functionally, the content is identical to the 6.0.0-v6alpha package we trialled couple days ago. 

@rynowak @glennc And Polly.Extensions.Http v2.0.1 in the same timeframe, as agreed.

@rynowak @glennc Thanks to you and the wider ASPNET Core team for the teamwork to get this best versioning/strong-name strategy in the market.

**Comment by joelhulen** [comment]
@iancooper @rynowak @glennc Polly v6.0.1 and Polly.Extensions.Http v2.0.1 (both RTM) have now been published to nuget.org. Thanks to each of you for raising the issue, and helping work to the best path forward. Thanks to @reisenberger for pushing hard the last few days to get these changes in place!

**Comment by rynowak** [comment]
6194618 in release/2.1

**Comment by iancooper** [comment]
Thanks all. We'll get to work.
