### ISSUE TITLE
Handle transient errors with basic retry support without Polly dependency

### ISSUE THREAD

**Issue by DalSoft** [aspnet/HttpClientFactory#111]
I created a retry handler for my RestClient that requires no third party dependencies, it handles and retries transient exceptions. It's based on a lot of feedback and use in the field. Let me know if your interested and I'll be happy to create a PR based off this work.

https://github.com/DalSoft/DalSoft.RestClient/blob/master/DalSoft.RestClient/Handlers/RetryHandler.cs

**Comment by glennc** [comment]
Did you ship this as a package on NuGet? I am good with linking to it from here if you do. We've started with that concern being handled by plugging in an extra package and I think we should continue that, but we can link to both Polly and this.

**Comment by rynowak** [comment]
Closing since this is answered
