### ISSUE TITLE
HttpClientFactory causing issues when using Azure Functions

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/HttpClientFactory#112]
When attempting to using HttpClientFactory from within an Azure Function the Function fails to run; this looks to be related to the versions of the DependencyInjection and other assemblies that use a higher version than WebJobs; please target the minimum required version so to allow use from within Azure Functions/WebJobs

**Comment by mkArtakMSFT** [comment]
Hi @grahamehorner.

`HttpClientFactory` class targets ASP.NET Core 2.1, and there are no any plans to backport it to earlier versions of the framework.
We do use new features added to 2.1. You can additionally try to compile the code against the version you're interested in.
