### ISSUE TITLE
Q: PolicyHandler DependencyInjection of services 

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/HttpClientFactory#114]
I’m looking to write a custom policy handler that require access to a distributed caching provider registered with DI, is it possible to access a IServiceCollection or IServiceProvider from the policy handler ? If so how would this be done?

**Comment by rynowak** [comment]
You can register your handler as a **TRANSIENT** in DI and wire it up like this:

```
services.AddHttpClient(...).AddHttpMessageHandler<MyHandler>();
```

Of you can do something like:
```
services.AddHttpClient(...).AddHttpMessageHandler(s => new MyHandler(s.GetRequiredService<MyCache>()));
```

https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L108

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
