### ISSUE TITLE
Missing methods for typed client - AddHttpClient<TClient, TImplementation> with serviceProvider

### ISSUE THREAD

**Issue by Ermesx** [aspnet/HttpClientFactory#116]
Hello,

I'm trying to do something like this:
```c#
services.AddHttpClient<ISomeClient, SomeTypedImplementation>(client =>
    {
        client.BaseAddress = new Uri("http://my.api.address.com");
    })
```

I want to set base address from configuration by options mechanism but I can't resolve it because there is no overload for this method with `IServiceProvider`.

Exists method for vanilla `HttpClient`:

``` c#
public static IHttpClientBuilder AddHttpClient(this IServiceCollection services, string name, Action<IServiceProvider, HttpClient> configureClient)
```

but there is no the same equivalent for typed clients:

``` c#
public static IHttpClientBuilder AddHttpClient<TClient, TImplementation>(this IServiceCollection services, string name, Action</*MISSING*/IServiceProvider, HttpClient> configureClient)
```

I think I can provide PR in this week for it.

**Comment by martincostello** [comment]
Use the [`ConfigureHttpClient()`](https://github.com/aspnet/HttpClientFactory/blob/5bb701daaa087dd8dc0f0a882117e316675dda6d/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L46) method on the builder returned by `AddHttpClient()`.

**Comment by Ermesx** [comment]
Works well, but extensions still looks like inconsistent. Should I prepare PR for it or leave it as is ? :)

**Comment by rynowak** [comment]
I'd be ok with adding this since it's a pretty common case. Feel free to send us a PR, it should be easy to figure out based on what's already there. 👍

**Comment by rynowak** [comment]
Merged! Thanks for the PR
