### ISSUE TITLE
What package is this class distributed in?

### ISSUE THREAD

**Issue by dave-hillier** [aspnet/HttpClientFactory#117]
I'd like to create a class library that depends on `HttpClientFactory`

Do I have to add a reference to `Microsoft.AspNetCore.App` or can I use a closer reference?

**Comment by martincostello** [comment]
You should be able to just reference `Microsoft.Extensions.Http`, I believe.

**Comment by dave-hillier** [comment]
It doesnt seem to work, the interface is in there.

**Comment by dave-hillier** [comment]
Found it: `Microsoft.AspNet.WebApi.Client`

**Comment by martincostello** [comment]
I think that's an old and completely different type that pre-dates .NET Core.

The concrete implementation of `IHttpClientFactory` is [`DefaultHttpClientFactory`](https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs) which you would access via DI as it's `internal`.

**Comment by dave-hillier** [comment]
That package is a current dependency of AspNetCore

https://www.nuget.org/packages/Microsoft.AspNetCore.App/2.1.0-rc1-final

**Comment by martincostello** [comment]
Yeah, I think they fixed it up to target netstandard so that some of the "old" utility extension methods for working with HttpClient could be used again.
