### ISSUE TITLE
Method not found 'CreateClient' when running as a Windows Service

### ISSUE THREAD

**Issue by ictoba** [aspnet/HttpClientFactory#123]
#### Issue description
When using the IHttpClientFactory in ASP.NET Core application that is supposed to be run as a Windows Service, it will generate the following error when run in Visual Studio 2017:
> MissingMethodException: Method not found: 'System.Net.Http.HttpClient System.Net.Http.HttpClientFactoryExtensions.CreateClient(System.Net.Http.IHttpClientFactory)'.

#### Details about environment
Windows 10 Pro 14393
Visual Studio 2017 15.5.0
.Net Framework 4.7.1 461310

#### Additional details / screenshot
Here is a minimal sample project that I created from scratch to replicate the issue.
[Sample project](https://drive.google.com/open?id=1PSAg7AhsCA07Odhmf1RXFKEpatBl7BEq)

**Comment by abatishchev** [comment]
Probably very related issue/question: this the whole new thing plays out nicely for calls from within my web app to another web app. But what about calling my web app from the outside? Service Fabric service in particular.

**Comment by rynowak** [comment]
@ictoba - this runs successfully for me if a debug from VS

What steps do I need to take to reproduce the problem?

**Comment by rynowak** [comment]
@abatishchev - if you have a problem I suggest creating a new issue

**Comment by abatishchev** [comment]
I've figured this out here: https://github.com/aspnet/HttpClientFactory/issues/54#issuecomment-395480415

**Comment by ictoba** [comment]
Hi @rynowak 
Thank you for taking your time to look into this issue.
Unfortunately I can't reproduce this anymore, not in the demo project and not in my actual project.
It was really weird because it was happening in a new project so a Visual Studio restart was not fixing the issue :|

The fix was restarting the system.
Please close the issue.
Big thanks Ryan! :D

**Comment by rynowak** [comment]
OK, your wish is my command
