### ISSUE TITLE
IDisposable and transient handlers that are injected

### ISSUE THREAD

**Issue by theezak** [aspnet/HttpClientFactory#124]
Hi,

There seems to be a conflict between the cached lifetime of a handler and the container calling IDisposable. Even when transient the container will dispose of the handler before the handler expires in the cache. We are running Autofac, but there are other containers with similar behavior.

**Comment by rynowak** [comment]
Can you provide some more information here or preferably a repo project? I'm not sure what you're referring to.

**Comment by theezak** [comment]
The following scenario can occur: a dependency scope is created and within that dependency scope a handler is resolved. The handler can however outlast the scope and be used in other scopes as well since the lifetime of the handler is tied to the cache plus additional time needed for all references to be released. This makes the handler a captive dependency. Only way of avoiding this issue and still utilize the cache would be to resolve Owned<THandler> (Autofac specific) and have the httpClient factory control the lifetime of the scope.

 Since the handler also implements IDisposable, the container will be default dispose the handler when the scope it was created in ends, but fortunately in the provided implementation the container realizes the handler is still referenced and will not dispose it.

**Comment by rynowak** [comment]
The expectation is that any handlers provided to the factory are **transient**. This is already covered in the doc comments and docs.asp.net, but perhaps it's not clear. The factory manages the lifetime of the handler pipeline and you are correct that it can outlive a scope. 

Is there a suggestion or a request here for something we can do make this more obvious or easier?

**Comment by theezak** [comment]
even when transient, they have to come from a scope:

when you use the root, there is a memory leak when resolved through dependency injection because the container will keep a reference to anything that implements IDisposable. 

When you use a child scope, the handler becomes a captive dependency and can be disposed by the container while the handler is still in use.

it appears to me that there is no clean way of using DI for these handlers (choice between memory leak or captive dependencies) without the cache controlling the life time of the handler.

**Comment by rynowak** [comment]
See comments here: https://github.com/aspnet/HttpClientFactory/issues/134#issuecomment-412366332 for how I'm planning to address this.

**Comment by rynowak** [comment]
Fixed for 2.2.0-preview2
