### ISSUE TITLE
Access to IServiceProvider in AddHttpClient action overload.

### ISSUE THREAD

**Issue by kieronlanning** [aspnet/HttpClientFactory#125]
Is possible to get hold of an `IServiceProvider` during the building of a `HttpClient`?

All of the samples referenced - here and on the release blog posts, include hard-coded uris for `BaseUrl` and other headers.

Is there an overload that takes an `IServiceProvider` so we can retrieve config and the like from things like `IOptionsSnapshot<T>` to enable configuration updates, or just one time config via `IOptions<T>`.

**Comment by martincostello** [comment]
Yep, various overloads are available that allow the `IServiceProvider` available. For example here’s some code of mine where I reach into my config to set the BaseAddress for a typed client: https://github.com/martincostello/alexa-london-travel-site/blob/c9a1dd2ac31908d1da61fdd03aade657ee9bea49/src/LondonTravel.Site/Extensions/HttpServiceCollectionExtensions.cs#L43

**Comment by kieronlanning** [comment]
Thanks @martincostello, also good to see the Tfl using .NET Core 2.1...!
