### ISSUE TITLE
Allow registration with another DI containers

### ISSUE THREAD

**Issue by karelkral** [aspnet/HttpClientFactory#127]
I want to use HttpClientFactory described here in my NET Framework 4.7.1. desktop application. My application is using Unity IoC. I referenced Microsoft.Extensions.Http as NuGet.

ASP.Net Core components are bound to Microsoft DI framework for .NetCore - IServiceCollection. In example, registration of HttpClientFactory is here:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient();
}

```
I was going deeper into your code and wanted to manually register corresponding interfaces and classes to Unity. This is how services are registered by IServiceCollection:

```cs
services.TryAddTransient<HttpMessageHandlerBuilder, DefaultHttpMessageHandlerBuilder>();
services.TryAddSingleton<IHttpClientFactory, DefaultHttpClientFactory>();

```
This would be no problem to move this to Unity IoC, but I am stucked when I want to register DefaultHttpMessageHandlerBuilder and DefaultHttpClientFactory which have **internal** visibility. So they are not available for registration outside of MS code.

Do I have any chance how to resolve this situation? If the classes were not internal, everything will work with another IoC containers also.

**Comment by khellang** [comment]
You should be able to use the Unity.Microsoft.DependencyInjection adapter to register what you need in the container. See its [`ServiceProviderFactory`](https://github.com/unitycontainer/microsoft-dependency-injection/blob/master/src/ServiceProviderFactory.cs). Just create an instance by passing in your container and call `CreateBuilder` with the service collection.

**Comment by mkArtakMSFT** [comment]
Thanks @khellang.
@karelkral, can you please confirm that the suggestion above worked for you?

**Comment by khellang** [comment]
Ideally you'd want to call [this method](https://github.com/unitycontainer/microsoft-dependency-injection/blob/master/src/Configuration.cs#L15), but for some reason, it's internal. // @ENikS

**Comment by ENikS** [comment]
Normally, you would add it to ``IServiceCollection`` before calling build. If you want to add registration at later point you could use ``RegisterType<>()`` on the container.

For example of how to use it with Unity please see [this project](https://github.com/unitycontainer/examples/blob/master/src/AspNetCoreExample/Startup.cs)

Notice how you add services to ``IServiceCollection`` in [ConfigureServices](https://github.com/unitycontainer/examples/blob/3d7a9beef54e0095541404ecb0e8b15645101954/src/AspNetCoreExample/Startup.cs#L26) and register types with container directly in [Configuration](https://github.com/unitycontainer/examples/blob/3d7a9beef54e0095541404ecb0e8b15645101954/src/AspNetCoreExample/Startup.cs#L16) methods.

**Comment by khellang** [comment]
Yeah, but that sample shows ASP.NET Core. It's not as straight-forward to do in a desktop application. That's why OP needs to use `IServiceCollection` and use that to populate the Unity container.

> If you want to add registration at later point you could use RegisterType<>() on the container.

The problem is that the types to register are internal, so you need to call the `IServiceCollection` extension method to be able to register them.

**Comment by ENikS** [comment]
I do not think I understand the issue. 
- Initialize your list with whatever calls you need
- Request Unity adapter and pass it the list

What am I missing?

**Comment by xlegalles** [comment]
And what about Castle Windsor (or any other one)? 
What you provide is just a workaround and I'm afraid that it will be very difficult to have a clean way to implement a custom container: mainly because you mix a service locator (IServiceProvider) with DI which is really "surprising"...

**Comment by karelkral** [comment]
Thank you, solution with Unity.Microsoft.DependencyInjection works!

Based on @davidfowl answer, I have used his second solution and completed code:

These packages need to be referenced from my project (snippet from .csproj):

```
     <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http">
          <Version>2.1.1</Version>
        </PackageReference>
        <PackageReference Include="Unity.Microsoft.DependencyInjection">
          <Version>2.0.10</Version>
        </PackageReference>
      </ItemGroup>
```

And here is the test that services from ServiceCollection can be resolved from Unity container:
```
    using System;
    using System.Linq;
    using System.Net.Http;
    using Microsoft.Extensions.DependencyInjection;
    using Unity;
    using Unity.Microsoft.DependencyInjection;
    using Xunit;
    
    namespace FunctionalTests
    {
    	public class UnityWithHttpClientFactoryTest
    	{
    
    		/// <summary>
    		/// Integration of Unity container with MS ServiceCollection test
    		/// </summary>
    		[Fact]
    		public void HttpClientCanBeCreatedByUnity()
    		{
    			UnityContainer unityContainer = new UnityContainer();
    
    			ServiceCollection serviceCollection = new ServiceCollection();
    			serviceCollection.AddHttpClient("Google", (c) =>
    			{
    				c.BaseAddress = new Uri("https://google.com/");
    			});
    			serviceCollection.BuildServiceProvider(unityContainer);
    
    			Assert.True(unityContainer.IsRegistered<IHttpClientFactory>());
    			IHttpClientFactory clientFactory = unityContainer.Resolve<IHttpClientFactory>();
    			HttpClient httpClient = clientFactory.CreateClient("Google");
    
    			Assert.NotNull(httpClient);
    			Assert.Equal("https://google.com/", httpClient.BaseAddress.ToString());
    
    		}
    
    	}
    }
```
