### ISSUE TITLE
Get travis and appveyor working

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#13]
Still not working, despite many broken promises

**Comment by rynowak** [comment]
Also I think the readme will need to be updated, I think the link for Appveyor is wrong

**Comment by Eilon** [comment]
Travis and AppVeyor both enabled. I'll leave it to you to update readmes, settings, etc.

**Comment by rynowak** [comment]
Remind me to talk to you about a thing tomorrow.

**Comment by rynowak** [comment]
This PR still doesn't have appveyor - let's look at it together tomorrow when you get in https://github.com/aspnet/HttpClientFactory/pull/15

**Comment by Eilon** [comment]
DONE
