### ISSUE TITLE
Error -  Unable to resolve service for type System.Net.Http.HttpClient

### ISSUE THREAD

**Issue by PradeepLoganathan** [aspnet/HttpClientFactory#130]
I am creating a typed HTTPClient in .net Core 2.1 as below

```cs
public class ScoreAPIClient : IScoreAPIClient
{
    HttpClient _client ;
    public ScoreAPIClient (HttpClient httpClient)
    {
          this._client = httpClient ?? throw new ArgumentNullException(nameof(httpClient)); 
    }
    
    public Score GetScore()
    {
       //impl
    }
}

public interface IScoreAPIClient
{
       Score GetScore();
}

//In my controller I inject IScoreAPIClient as below

[Route("api/[controller]")]
[ApiController]
public class ScoreAPIGatewayController : ControllerBase
{
    IScoreAPIClient _client;

    public ScoreAPIGatewayController (IScoreAPIClient scoreClient}
    {
        _client = scoreClient;
    }
}
//In startup i register the typed HttpClient as below

public void ConfigureServices(IServiceCollection services)
{
     services.AddHttpClient<ScoreAPIClient>();
     services.AddTransient<IScoreAPIClient , ScoreAPIClient >();
}

````

Wheh i run the above code i expect the DI to inject ScoreAPIClient into the controllers constructor and the HttpClient into the ScoreAPIClient constructor. However i get an error as below...

System.InvalidOperationException: Unable to resolve service for type System.Net.Http.HttpClient while attempting to activate ScoreAPIClient   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)&#xD;&#xA;   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)&#xD;&#xA;   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)&#xD;&#xA;   at lambda_method(Closure , IServiceProvider , Object[] )&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.&lt;&gt;c__DisplayClass4_0.&lt;CreateActivator&gt;b__0(ControllerContext controllerContext)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.&lt;&gt;c__DisplayClass5_0.&lt;CreateControllerFactory&gt;g__CreateController|0(ControllerContext controllerContext)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()&#xD;&#xA;   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA;   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context

I am unable to figure out what am I doing wrong. Why is DI failing to create HttpClient ?

**Comment by PradeepLoganathan** [comment]
I resolved this by passing in ScoreAPIClient  into the constructor rather than IScoreAPIClient .

**Comment by stevejgordon** [comment]
@PradeepLoganathan - You should also be able to register the service as follows...
```
public void ConfigureServices(IServiceCollection services)
{
     services.AddHttpClient<IScoreAPIClient, ScoreAPIClient>();
}
```

**Comment by PradeepLoganathan** [comment]
@stevejgordon Thanks for responding.  Unfortunately, that fails with a DI error. Not sure if I am doing anything wrong.  The error is as below - 

System.InvalidOperationException: Unable to resolve service for type ;ScoreCard.ScoreCardGateway.Clients.ScoreCardAPIClient while attempting to activate  ;ScoreCard.CandidateGateway.Controllers.ScoreCardAPIGatewayController   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)   at lambda_method(Closure , IServiceProvider , Object[] )at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.__DisplayClass4_0.<CreateActivator;b__0(ControllerContext controllerContext)   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>;c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State; next, Scope; scope, Objectstate, Boolean isCompleted)  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State next, Scope scope, Object state, Boolean isCompleted)   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)  at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

The code in ConfigureServices changed based on your suggestion to below -- 
```cs
public void ConfigureServices(IServiceCollection services)
{
     services.AddHttpClient<IScoreAPIClient, ScoreAPIClient>();
}
```

**Comment by PradeepLoganathan** [comment]
Nope my bad. I changed the controller to below and it worked. I had not reverted controller code from earlier. Thanks @stevejgordon . I have been following your post to get this done. :-)

```cs
public ScoreCardAPIGatewayController(IScoreAPIClient scoreClient)
{
       this._scoreClient= scoreClient;
}

```

**Comment by SekulKamberov2** [comment]
Try this in Startup.cs
services.AddHttpClient<IScoreAPIClient , ScoreAPIClient >();
