### ISSUE TITLE
Access to IServiceProvider inside typed client configuration delegate

### ISSUE THREAD

**Issue by MarcoNicolodi** [aspnet/HttpClientFactory#131]
Hi.

I would like to acess do IServiceProvider inside the configuration delegate with a TypedClient the same way it works for the named client:

```csharp
services.AddHttpClient("AdminApi", (provider, client) =>
            {
                var context = provider.GetService<IUserContext>();
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", context.Token);
                client.BaseAddress = new Uri(Configuration["AdminClient:Url"]);
            });
```

But if register a typed client, the delegate has only access to the IHttpClient. Why is that? 

This might be a feature request. I know that I might be flooding your issue tracker and im sorry for that because you are being working so hard, but I didnt found any explanation for that. 

I already solved my issue using a named client, and getting it instance though the service provider and then injecting it into the service i want, but it would be way more elegant just using the typed client.

Thank you.

**Comment by rynowak** [comment]
You can do it in two steps.
```
services.AddHttpClient("AdminApi", (provider, client) =>
{
                var context = provider.GetService<IUserContext>();
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", context.Token);
                client.BaseAddress = new Uri(Configuration["AdminClient:Url"]);
})
.AddTypedClient<MyClient>();
```
`AddHttpClient()` returns a builder that you can use for more stuff. 

We also added an additional overload in 2.2 (dev branch) to do this in one step. This has come up a few times.

**Comment by rynowak** [comment]
Closing this because I think I answered the question. Let me know if this doesn't fix it.
