### ISSUE TITLE
No way to inject HttpClientHandler using the DefaultHttpClientFactory

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [aspnet/HttpClientFactory#139]
Is it possible to inject a custom HttpClientHandler so that I can put in my own custom ServerCertificateCustomValidationCallback without having to implement my own IHttpClientFactory? Without that functionality I am kinda lose all the great functionality that is already built in.

Kind Regards,

Jason Wyglendowski

**Comment by martincostello** [comment]
You can use the [`ConfigurePrimaryHttpMessageHandler()`](https://github.com/aspnet/HttpClientFactory/blob/0677ac9f1e3efeb7557291ed42c726c60bde9c93/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L169) method on the builders to configure the primary handler by creating a `HttpClientHandler` and setting the properties you need to modify.

**Comment by jwyglendowski-precisionlender** [comment]
@martincostello Thanks. I am just posting the code below for future reference and hopefully that will get documented somewhere :). 

`
      HttpClientHandler handler = new HttpClientHandler();
                
      handler.ServerCertificateCustomValidationCallback = (msg, cert, chain, errs) => {
                if (errs == SslPolicyErrors.None)
                {
                    return true;
                }
                return false;
            };

            services.AddHttpClient("client")
                .ConfigurePrimaryHttpMessageHandler(config => {
                    return handler;

**Comment by martincostello** [comment]
You should always create a new instance in the delegate specified to `ConfigurePrimaryHttpMessageHandler()`, otherwise you'll negate benefits such as the HTTP message handler rotation.

**Comment by jwyglendowski-precisionlender** [comment]
Okay. So it will make that change to my code. Thanks for your help.

**Comment by jwyglendowski-precisionlender** [comment]
`
    services.AddHttpClient("client")
                .ConfigurePrimaryHttpMessageHandler(config => {
                    HttpClientHandler handler = new HttpClientHandler();
                
                    handler.ServerCertificateCustomValidationCallback = (msg, cert, chain, errs) => {
                        if (errs == SslPolicyErrors.None)
                        {
                            return true;
                        }
                        return false;
                    };

                    return handler;
                });
`
