### ISSUE TITLE
Override Default logging

### ISSUE THREAD

**Issue by nishantkagrawal** [aspnet/HttpClientFactory#141]
Is there a way to override the default logging or disable it?

**Comment by rynowak** [comment]
Can you tell us a little more about what you want to do?

**Comment by martincostello** [comment]
More detailed logs are available in-box at `Trace` level, but then you may encounter performance issues with the sheer amount of data produced at runtime, plus also potentially logging sensitive information such as authorisation headers.

If you need to customise the logs, a custom message handler is the way to go. You should just then filter out messages from the in-box logging in your configuration if you don’t want duplicates: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#log-filtering

**Comment by rynowak** [comment]
If you want to take control and implement your own thing, I'd suggest removing the default implementation of `IHttpMessageHandlerBuilderFilter` from services and writing your own.

If you follow all of the links here, you'll see how our default logging implementation is stitched together.
https://github.com/aspnet/HttpClientFactory/search?q=IHttpMessageHandlerBuilderFilter&unscoped_q=IHttpMessageHandlerBuilderFilter

I'm also interested if you have ideas about how to make the logging better or more configurable.

**Comment by stevejgordon** [comment]
@rynowak I've been meaning to blog about the logging included in `IHttpClientFactory` for a while. This piqued my interest again so I'll aim to blog a simple example of what you suggest here too.

**Comment by stevejgordon** [comment]
I've completed and published my post about the logging in HttpClientFactory + added an additional piece around @rynowak's suggestion above to swap out the filter - https://www.stevejgordon.co.uk/httpclientfactory-asp-net-core-logging

**Comment by nishantkagrawal** [comment]
@rynowak : While logging one of the thing that we always want to log is the correlation id. Also for all outgoing http requests via httpclient, we log an extra operation id for all the logs for the specific HttpClient, that helps us to filter the logs to a specific HttpOperation. That's the primary reason why I would like to override the default logger within HttpClient. 

@stevejgordon : I looked at your blog post and it looks awesome. In my case, I just created another MessageHandler instead of overriding the logs created by default, and filtered the default logs within the log4net framework.

**Comment by glennc** [comment]
Looks like we've answered the question, so I'm going to close this. I also think we should put an issue on the backlog about building something that lets you configure what you want to log and log it, it's a feature we've talked about but haven't really started designing or working on.
