### ISSUE TITLE
Format of log messages for unnamed clients

### ISSUE THREAD

**Issue by stevejgordon** [aspnet/HttpClientFactory#142]
REPRO: Create a client directly using the factory, without providing a name.

`var client = factory.CreateClient();`

Ensure at least information logging is enabled, make a request and view the resulting log messages.

You will see that where no name exists the log message includes a double full stop (period) character before LogicalHandler.

`System.Net.Http.HttpClient..LogicalHandler[100]`

I believe the message should either remove the unnecessary period or perhaps use "Default" where the name is empty. I'm happy to put in a PR to address this, I would just need to know what the preferred solution should be in this case.

This is non-urgent so I would propose this for the 2.2 timeframe.

**Comment by rynowak** [comment]
I think we should use `default` in this case.  - so the whole name would be `System.Net.Http.HttpClient.default.LogicalHandler`.

Feel free to send a PR 😆

**Comment by stevejgordon** [comment]
@rynowak Happy to pop in a PR. Do you think this should be limited to the point of naming the loggers? Or would setting the name on clients to default rather than an empty string be preferred? I'm not sure if there's a reason it used the Options.DefaultName currently?

**Comment by rynowak** [comment]
Yes, it uses `Options.DefaultName` on purpose. That way if you use the methods provided by options to interact with the client factory, it will affect the default client. Basically the design of named clients piggybacks on an existing feature.
