### ISSUE TITLE
Contribution guidelines link is broken

### ISSUE THREAD

**Issue by kevbry** [aspnet/HttpClientFactory#147]
The link to the Home repo contribution guidelines is incorrect.

New contributor popover links to:
https://github.com/aspnet/HttpClientFactory/blob/master/CONTRIBUTING.md

Which currently leads to:
https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md

Instead should lead to:
https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md

**Comment by Eilon** [comment]
Will fix!

**Comment by Eilon** [comment]
Fixed!
