### ISSUE TITLE
Cannot configure HttpClientHandler for non-named clients

### ISSUE THREAD

**Issue by Berreek** [aspnet/HttpClientFactory#149]
### Description
There is an issue when trying to configure HttpClientHandler for a non-named client. For some reason client is configured with default instance of HttpClientHandler instead of one that was configured. If I configure client with the name then it works as expected.

### Reproduce
```C#
public class Program
{
     public static void Main(string[] args)
     {
         var collectionWithNonNamedClient = new ServiceCollection();
         collectionWithNonNamedClient
             .AddHttpClient<TestHttpClient>()
             .ConfigurePrimaryHttpMessageHandler(() =>
                 new HttpClientHandler {AutomaticDecompression = DecompressionMethods.GZip});

         // automatic decompressions here is set as none
         var client = collectionWithNonNamedClient
                               .BuildServiceProvider()
                               .GetService<IHttpClientFactory>()
                               .CreateClient();

         var collectionWithNamedClient = new ServiceCollection();
         collectionWithNamedClient
             .AddHttpClient<TestHttpClient>("foo")
             .ConfigurePrimaryHttpMessageHandler(() =>
                 new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip });

         // here it's fine
         var anotherClient = collectionWithNamedClient
                                .BuildServiceProvider()
                                .GetService<IHttpClientFactory>()
                                .CreateClient("foo");
     }
}

public class TestHttpClient : HttpClient
{
}
```

**Comment by martincostello** [comment]
When you use `AddHttpClient<T>()`, the name of `T` is used to configure the client as per this code: https://github.com/aspnet/HttpClientFactory/blob/0677ac9f1e3efeb7557291ed42c726c60bde9c93/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L200

You'd need to call `CreateClient("TestHttpClient")` to get your custom client as an instance `HttpClient`.

**Comment by Berreek** [comment]
Right, my bad with it then. 
What about configuring `HttpClientHandler` for non-named `HttpClient` ? That was my main goal and that's why I tried to play with generic method a bit.
`AddHttpClient()` does not expose IHttpClientBuilder - is there any reason for it ?

**Comment by martincostello** [comment]
You can configure the default `HttpClient` this way

```csharp
AddHttpClient(Microsoft.Extensions.Options.Options.DefaultName)
```

https://github.com/aspnet/HttpClientFactory/blob/0677ac9f1e3efeb7557291ed42c726c60bde9c93/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L63

This returns an `IHttpClientBuilder`, allowing you to change the default setup.

I believe the `AddHttpClient()` method is just intended to add the services to the `IServiceCollection`, which is why it doesn't return the builder.

**Comment by Berreek** [comment]
That works fine. Thanks for your help.
