### ISSUE TITLE
Manually closing HttpClientMessage handlers

### ISSUE THREAD

**Issue by alexanderman** [aspnet/HttpClientFactory#150]
Hi, I have a question, I'm working on service that is responsible for making web api requests through proxy server. I use SetHandlerLifetime to configure the lifetime of handlers.
Is there a way to have more control over HttpClientMessage handlers and close them manually, and by doing this causing the factory to create new ones?

**Comment by rynowak** [comment]
We don't have a feature like this today - what would be your ideal solution? Do you want the ability to create a client with an 'untracked' handler?

**Comment by glennc** [comment]
I am interested in knowing more about the scenario you are in before we design a solution. What logic would you use to determine you need to recycle the handler? How do you know the IP address has changed for example. Is it just that you need a shorter timespan for the recycling of the handlers.

**Comment by alexanderman** [comment]
Hi @glennc , I'm trying to copy the logic from here https://github.com/luminati-io/api/blob/master/csharp/high_perf.cs using the factory.

**Comment by glennc** [comment]
Need some time to look over what's happening there. I'll get back to you :)

**Comment by alexanderman** [comment]
Thank you, @glennc

**Comment by glennc** [comment]
Would your problem be solved by implementing `IWebProxy` and deferring to an actual implementation, with your logic to recycle that type internal proxy periodically? I am making an assumption that creating a new proxy object will get you a new IP and that would solve your issues. You let the connection stuff be handled

**Comment by alexanderman** [comment]
that's the exact solution I eventually implemented, 10x ))

**Comment by rynowak** [comment]
@alexanderman - I'm going to close this then, it seems like there was a better fix for you issue
