### ISSUE TITLE
AddHttpClient should still work even if called before AddSingleton

### ISSUE THREAD

**Issue by joshlang** [aspnet/HttpClientFactory#162]
```
	class Program
	{
		//<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
		//<PackageReference Include = "Microsoft.Extensions.Http" Version="2.1.1" />
		class Blarg
		{
			public Blarg(HttpClient c) { }
		}
		static void Main(string[] args)
		{
			ServiceCollection sc = new ServiceCollection();
			sc.AddSingleton<Blarg>();
			sc.AddHttpClient<Blarg>();
			sc.BuildServiceProvider().GetRequiredService<Blarg>(); // OK

			sc = new ServiceCollection();
			sc.AddHttpClient<Blarg>();
			sc.AddSingleton<Blarg>();
			sc.BuildServiceProvider().GetRequiredService<Blarg>(); // System.InvalidOperationException: 'Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'ConsoleApp3.Program+Blarg'.'
		}
	}
```

In the project above, the first service provider works without any problem.  But the second one crashes with an exception.

I got trapped by this.  I didn't realize that I needed to call AddSingleton *before* I called AddHttpClient or else I would get an exception.  Took me a while to figure it out.

I don't know why it makes a difference.  Maybe there's a reason?  But if not, it would probably better to make it work either way.

**Comment by khellang** [comment]
> Maybe there's a reason?

The reason is that the order you register stuff in the container matters 😉

When resolving a service, the last registration is used. In the latter case, that's a regular singleton registration, which doesn't know how to resolve `System.Net.Http.HttpClient`, unlike the `AddHttpClient` registration.

Why are you registering the service twice?

**Comment by joshlang** [comment]
Oi!!

I didn't realize I was registering it twice.  I thought AddHttpClient was registering the HttpClient which is depended on by the Blarg class.

It seems rather that AddHttpClient registers Blarg too.  Makes me wonder what happens with other dependencies if there were some.

Maybe that's a job for IHttpClientFactory instead!

But ok.  I understand for now.  Thanks!

**Comment by khellang** [comment]
Right, there are a couple of overloads for `AddHttpClient`. One non-generic overload that just adds the infrastructure services, like `IHttpClientFactory`:

https://github.com/aspnet/HttpClientFactory/blob/6fae77bfaa08e509ca34817d08d4f5e7d019e343/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L22-L52

And the generic overload that you're calling:

https://github.com/aspnet/HttpClientFactory/blob/6fae77bfaa08e509ca34817d08d4f5e7d019e343/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L191-L205

As the XML docs say:

> The type of the typed client. They type specified will be registered in the service collection as a transient service. See `ITypedHttpClientFactory<TClient>` for more details about authoring typed clients.

**Comment by joshlang** [comment]
Got it.

I'll close this.  Thanks for clearing it up.
