### ISSUE TITLE
Clarification on httpclient/handler reuse

### ISSUE THREAD

**Issue by disophisis** [aspnet/HttpClientFactory#163]
I just wanted some clarification on how httpclients and httpclienthandlers are reused by the httpclientfactory when using typed clients.

Say if I have two client classes which have the same ```BaseAddress```, but those clients are functionally different.  Will ```ClientOne``` and ```ClientTwo``` be assigned the same resources under the hood?  Or will two separate httpclients with the same ```BaseAddress``` be created?

```
services.AddHttpClient<IClientOne, ClientOne>()
	.ConfigureHttpClient((client) =>
	{
		client.BaseAddress = new Uri(servicesConfiguration.Uris.UriTest);
	});
services.AddHttpClient<IClientTwo, ClientTwo>()
	.ConfigureHttpClient((client) =>
	{
		client.BaseAddress = new Uri(servicesConfiguration.Uris.UriTest);
	});
```

**Comment by rynowak** [comment]
In this case separate `HttpClient` instances will be created for each typed client, each time you request one. `HttpClient` is a thin wrapper around the actual resources, and it's mutable. The factory never pools `HttpClient` instances.

What we pool is `HttpMessageHandler` instances, and we one one 'active' handler per named client.
