### ISSUE TITLE
Make it easy to use HttpClients that come from the factory

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#17]
The tricky thing here is that we think *named clients* are the primary experience - and that doesn't directly work with DI because we don't have a way for you to provide a name when the container does injection.

We're considering experiences like the following:

**Layer 0: Just using the factory (duh)**
```
public class MyComponent
{
    public MyComponent(HttpClientFactory factory)
    {
        Client = factory.CreateClient("github");
    }

    public HttpClient Client { get; set; }
}

services.AddHttpClient("github", builder =>
{
    ...
});
```

**Layer 1: Registering a handle type**

Behind the scenes we'll register a factory function for your MyComponent class
```
public class MyComponent
{
    public MyComponent(HttpClient client)
    {
        Client = client;
    }

    public HttpClient Client { get; set; }
}

services.AddHttpClient<MyComponent>(builder =>
{
    ...
});
```

**Layer 2: Using MVC**

MVC's model binder will map a client to a name for you - doesn't work with DI.
```
public class MyController
{
    public HttpClient GithubClient { get; set; }

    public IActionResult DoThing()
    {
    }
}

services.AddHttpClient("github", builder =>
{
    ...
});
```

**Comment by davidfowl** [comment]
An alternate approach that's more DI friendly is something type based like logging:

```C#
[HttpClient("github")]
public class MyComponent
{
    public MyComponent(HttpClient<MyComponent> client)
    {
        Client = client;
    }

    public HttpClient<MyComponent> Client { get; set; }
}

services.AddHttpClient("github", builder =>
{
    ...
});
```

**Comment by rynowak** [comment]
Working POR here is to do something like `Level 1:` in the initial comment. This doesn't require more types and is DI/activation friendly. This will also work for refit style libraries.

Note that PR #31 already has this approach.
