### ISSUE TITLE
Microsoft.Extensions.Http.Polly.dll is code signed but Polly.Extensions.Http.dll and Polly.dll are not

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpClientFactory#170]
_From @abatishchev on August 31, 2018 18:45_

My Service Fabric + ASP.NET Core (API) application refers package Microsoft.Extensions.Http.Polly which contains Microsoft.Extensions.Http.Polly.dll which is code signed by Microsoft.

It refers two more packages: Polly.Extensions.Http -> Polly. Which respective dlls are not anyhow code signed. What raises an alerts when my application binaries are reaching our Test (PPE) environment.

How should I handle this? Code sign it myself, alongside with my own binaries? Would it be appropriate?

_Copied from original issue: aspnet/Security#1849_

**Comment by abatishchev** [comment]
@Tratcher thanks. can you edit the title to append "are not" at the end?

**Comment by rynowak** [comment]
hi @abatishchev - the best place for this feedback is https://github.com/App-vNext/Polly

Polly is a 3rd party project, which is not owned by Microsoft.

**Comment by Eilon** [comment]
Hi @abatishchev , we Authenticode-sign only stuff that we make or that we compile on our own. We don't sign pre-existing DLLs like this.

You can certainly add your own Authenticode signature to an existing DLL. Assuming this is for Microsoft work, there is a "Microsoft 3rd party" certificate you can select on the CodeSign site to add additional Authenticode certs to an existing DLL (or EXE, etc.).
