### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by ceccomil** [aspnet/HttpClientFactory#181]
Hi All,
The issue I'm experiencing it's a little bit hard to reproduce because it doesn't happen all the times. Basically, I'm creating a collection of typed HttpClients so the collection itself can be injected into DI pipeline to avoid a long list of different clients in constructors where needed.

Everything seems to be working just fine until all of the sudden, during the activation process, the initialization of the HttpClients collection fails with the error below, **which I believe it's referring to the services collection (IServiceCollection).**

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at KCA.Core.Api.HttpClientFactory.KCAHttpClients..ctor(IServiceCollection services, IEnumerable`1 options)
   at KCA.Core.Api.HttpClientFactory.Extensions.<>c__DisplayClass0_0.<AddKCAHttpClientsTransient>b__0(IServiceProvider sp)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

There are 4 key parts:
- IKCAHttpClient:  TypedHttpClient which describe the basic client functionalities
- IKCAHttpClients: Collection of IKCAHttpClient
- KCAHttpClient: implementation
- IKCAHttpClients: implementation

Interfaces:
```
public interface IKCAHttpClient : IDisposable
{

    void AddHeaders(IEnumerable<KCAHeader> headers);
    void RemoveHeaders(IEnumerable<KCAHeader> headers);


    Task<TApiResult> GetAsync<TApiResult>(string route, string query = null,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> PutAsync<TApiResult>(string route, object body,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> PostAsync<TApiResult>(string route, object body,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> DeleteAsync<TApiResult>(string route, string query = null,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;


    Task<TApiResult> GetBsonAsync<TApiResult>(string route, string query = null,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> PutBsonAsync<TApiResult>(string route, object body,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> PostBsonAsync<TApiResult>(string route, object body,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;

    Task<TApiResult> DeleteBsonAsync<TApiResult>(string route, string query = null,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class;
}
```
```
public interface IKCAHttpClients : IDisposable
{
    IKCAHttpClient this[string clientName] { get; }
}
```

Implementations:
```
public class KCAHttpClient : IKCAHttpClient
{
    private bool _IsDisposed = false;
    private readonly HttpClient _httpClient;

    public KCAHttpClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    private string GetUrl(string route, string query = null)
    {
        string url = _httpClient.BaseAddress.ToString();
        while (url.EndsWith("/"))
        {
            url = url.Remove(url.Length - 1);
        }

        url += "/";

        if (route.ToLower().StartsWith("http"))
        {
            url = "";
        }

        while (route.StartsWith("/"))
        {
            route = route.Substring(1);
        }

        if (query != null)
        {
            query = "?" + query;
        }

        url += route + query;

        return url;
    }

    public void AddHeaders(IEnumerable<KCAHeader> headers)
    {
        if (headers != null)
        {
            foreach (KCAHeader h in headers)
            {
                _httpClient.DefaultRequestHeaders.Add(h.HeaderKey, h.HeaderValue);
            }
        }
    }

    public void RemoveHeaders(IEnumerable<KCAHeader> headers)
    {
        if (headers != null)
        {
            foreach (KCAHeader h in headers)
            {
                _httpClient.DefaultRequestHeaders.Remove(h.HeaderKey);
            }
        }
    }

    public async Task<TApiResult> GetAsync<TApiResult>(string route, string query = null,
        string accessToken = null, IEnumerable<KCAHeader> additionalHeaders = null) where TApiResult : class
    {
        string url = GetUrl(route, query);
        if (accessToken != null)
            _httpClient.AddBearer(accessToken);

        AddHeaders(additionalHeaders);

        HttpResponseMessage response = await _httpClient.GetAsync(url);
        RemoveHeaders(additionalHeaders);
        if (response.IsSuccessStatusCode)
        {
            string result = await response.Content.ReadAsStringAsync();              
            return JsonConvert.DeserializeObject<TApiResult>(result);
        }
        else
            throw new Exception("Error while calling API (" +
                    url + ") status code: " + response.StatusCode);
    }

    //All the other methods...

    public void Dispose()
    {
        Dispose(true);
    }

    private void Dispose(bool disposing)
    {
        if (disposing && !_IsDisposed)
        {
            _IsDisposed = true;
            if (_httpClient != null)
            {
                _httpClient.Dispose();
                GC.SuppressFinalize(_httpClient);
            }
        }
    }
}
```

And finally the important bit:
```
public class KCAHttpClients : IKCAHttpClients
{
    private bool _IsDisposed = false;

    private Dictionary<string, IKCAHttpClient> HttpClients { get; set; }

    public IKCAHttpClient this[string clientName]
    {
        get
        {
            return HttpClients[clientName];
        }
    }

    internal KCAHttpClients(IServiceCollection services, IEnumerable<KCAHttpClientOptions> options)
    {
        try
        {
            HttpClients = new Dictionary<string, IKCAHttpClient>();
            
            //https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs

            int optionsCount = options.Count();
            for (int i = 0; i < optionsCount; i++)
            {
                var opt = options.ElementAt(i);
                //https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs
                services.Configure<HttpClientFactoryOptions>(opt.ClientName, httpClientConf => httpClientConf.HttpClientActions.Add((c) =>
                {
                    c.BaseAddress = new Uri(opt.ClientBaseAddress);
                    if (opt.PermanentHeaders != null)
                    {
                        foreach (KCAHeader h in opt.PermanentHeaders)
                        {
                            c.DefaultRequestHeaders.Add(h.HeaderKey, h.HeaderValue);
                        }
                    }
                }));

                //I've also tried a version (with the same result) in which this line below was before the for loop
                //just right after the init of HttpClients Dictionary
                IServiceProvider servProv = services.BuildServiceProvider();
                var httpClientFactory = servProv.GetRequiredService<IHttpClientFactory>();
                var typedClientFactory = servProv.GetRequiredService<ITypedHttpClientFactory<KCAHttpClient>>();

                var httpClient = httpClientFactory.CreateClient(options.ElementAt(i).ClientName);
                var client = typedClientFactory.CreateClient(httpClient);

                HttpClients.Add(options.ElementAt(i).ClientName, client);

                if (options.ElementAt(i).RequiredToBeSingleton)
                {
                    services.AddSingleton<IKCAHttpClient>(sp => client);
                }
                else
                {
                    services.AddTransient<IKCAHttpClient>(sp => client);
                }

            }
        }
        catch (Exception ex)
        {
            //This is where the "collection changed" error is thrown
            Log.Logger.Error("Error during KCAHttpClients initialization!", ex);
            throw ex;
        }

    }

    public void Dispose()
    {
        Dispose(true);
    }
    private void Dispose(bool disposing)
    {
        if (disposing && !_IsDisposed)
        {
            _IsDisposed = true;
            foreach (var client in HttpClients.Values)
            {
                if (client != null)
                {
                    client.Dispose();
                    GC.SuppressFinalize(client);
                }
            }
        }
    }
}
```

**Comment by martincostello** [comment]
I've seen a similar issue with service activation throwing the same exception, but I'm not sure whether or not that's from using `IHttpClientFactory` or not. It's happened probably a handful of times in the last few months.  If my memory serves correctly, `IOptions<T>` was involved.

That said, looking at your code, using an `IEnumerable<T>` all the way through has the potential for performance issues if you have to keep re-walking the enumerator if it's backed by a lazy implementation. I'd suggest materialising it into an `IList<T>` near the top of the method using `options.ToList()` so that you're operating on a set of a fixed size, and then you can use `Count` rather than `Count()` and an indexer rather than `ElementAt()`.

**Comment by ceccomil** [comment]
@martincostello Thanks for the answer.

>  I've seen a similar issue with service activation throwing the same exception

I'll have a look at the implementation of IOptions to see what could be wrong with it.

> I'd suggest materialising it into an IList<T>

I don't think it would be really different in my case since options is always of type KCAHttpClientOptions[] but, it won't cause any harm so I will follow your suggestion.

**Comment by slang25** [comment]
I would watch out for calling `services.BuildServiceProvider()`, you'll build your provider twice, which might be where some of the weirdness is coming from.

Remember that `services.AddSingleton(` and other overloads take a func that has the service provider, so try using that it this example.

Something like this maybe:

```csharp
IKCAHttpClient CreateKCAHttpClient(ServiceProvider sp)
{
    var httpClientFactory = sp.GetRequiredService<IHttpClientFactory>();
    var typedClientFactory = sp.GetRequiredService<ITypedHttpClientFactory<KCAHttpClient>>();

    var httpClient = httpClientFactory.CreateClient(options.ElementAt(i).ClientName);
    var client = typedClientFactory.CreateClient(httpClient);
    HttpClients.Add(options.ElementAt(i).ClientName, client);
    return client;
}

if (options.ElementAt(i).RequiredToBeSingleton)
{
    services.AddSingleton<IKCAHttpClient>(CreateKCAHttpClient);
}
else
{
    services.AddTransient<IKCAHttpClient>(CreateKCAHttpClient);
}
```

**Comment by rynowak** [comment]
Sorry I'm not sure I understand what's happening here. What are you trying to accomplish?

**Comment by ceccomil** [comment]
@rynowak Thanks for your reply. Basically, what I wanted to achieve was:

1) Having a middleware which can be initialized with options (from 1 to N HttpClients configurations such as base addresses, headers settings, etc... )
2) I wanted to have all the HttpClients in the collection created as ITypedHttpClientFactory<MyTypedClient>

So, for example, let's assume a controller needs 3 different HttpClients with the same behavior but different configurations. I'll have the configuration of the middleware in the startup class, then in the controller's constructor signature, I'll only need to include the IClientsCollection and not all the typed clients required and most important I don't have to define different "ITypedClient(s)"

Btw,  @slang25 pointed out something which I knew, the reason I was calling services.BuildServiceProvider() was because I couldn't get the required services otherwise and that was because of an error in my original implementation so... I've moved the "services.Configure<HttpClientFactoryOptions>(...." before initializing the ClientsCollection. I've also realized that for no reason I should have had to add each Client as single service ("services.Add...") since the collection itself has been already added by the time being.

Now my AddService extension looks like this below and everything is working like a charm.
```
public static IServiceCollection AddKCAHttpClientsTransient(this IServiceCollection services,
IEnumerable<IOptions<KCAHttpClientOptions>> options)
{
  services.ConfigureClientFactoryOptions(options);
  return services.AddTransient<IKCAHttpClients, KCAHttpClients>(sp =>
  {
    var httpClientFactory = sp.GetRequiredService<IHttpClientFactory>();
    var typedClientFactory = sp.GetRequiredService<ITypedHttpClientFactory<KCAHttpClient>>();

    return new KCAHttpClients(httpClientFactory, typedClientFactory, options);
  });
}
```

You can close the issue, which wasn't an HttpClientFactory issue afterall.
Many thanks.

**Comment by rynowak** [comment]
Ok, glad you figured it out!
