### ISSUE TITLE
HttpClientFactory Causes High CPU?

### ISSUE THREAD

**Issue by tbasallo** [aspnet/HttpClientFactory#184]
I've been searching for the cause of extremely high CPU usage on Azure. Two recent deployments of ASP.NET Core 2.1 (rewrites from 4.7, one with no front-end, strictly API) started spiking Azure to 100% and not letting go. Only adding multiple instances, multiple restarts and a lot of moving things would get it to reset itself.

Memory stays flat, doesn't move. It's only CPU.

I removed Application Insights, due to some possible CPU issues on 2.1 and the latest AI. Nothing (per issues)
Installed New Relic - didn't tell me anything useful (though it could be I didn't do all 8 components)

The only other major change for the API (which is the Spikee according to Azure) is the move to HttpClientFactory (both projects use it). I looked through the issues and didn't see any CPU related posts, I am wondering if anyone has seen anything similar. Trying to reproduce, but it's not a consistent issue. Thrice I thought I got it fixed and there she was the next I looked.

I stressed the API locally with 1200 calls to the external service and it didn't even notice I was calling it. 

The API only has 6 calls that call external services. Peaks at 100 requests/s and usually hovers around 30. When it goes past 30 it's when it (might) spikes. I moved the two heavy hitters (20-45 second calls) to Azure Functions, as I try to isolate the issue.

I just went back to static HttpClients to try and isolate the issue and ensure it's not the factory.

This is a 30 day view. The first spike was 2 days after deployment.

![image](https://user-images.githubusercontent.com/270673/46377590-fd186b80-c666-11e8-826c-66f3c09ee670.png)

**Comment by martincostello** [comment]
I had similar issues with CPU slowly rising, which I fixed by updating to the latest release of the Applications Insights assemblies at the time: martincostello/alexa-london-travel-site#215

**Comment by Eilon** [comment]
@sebastienros @rynowak - ideas?

**Comment by davidfowl** [comment]
You might be running into this https://github.com/aspnet/KestrelHttpServer/issues/2694?

**Comment by rynowak** [comment]
Closing this due to lack of response. If you want to provide some perf traces we can help investigate.

**Comment by tbasallo** [comment]
I've been meaning to come back.

The issue was not related to the factory. The high CPU usage returned after a few days. I am going to follow-up on @davidfowl's  post and hopefully that will get me somewhere.

Thanks.

**Comment by rynowak** [comment]
Alright, please let us know if we can do anything else to help.

**Comment by davidfowl** [comment]
If you can get a memory dump when this 100a% CPU happens I can take a look.

**Comment by tbasallo** [comment]
Thanks, @davidfowl Ever since I moved the 2 apps to their own plan, hitting 100% has been less frequent - more load is needed than before, I think, to cause whatever it is. Hopefully Monday when there's more concurrent users. 
I did see this pattern when looking at a 12 hour window. I've been trying to chase down a reason, but can't. There are no jobs, background tasks, scheduled events - nothing of the sort. Each one of those double spikes is 5% and 30% every 20 minutes.

![image](https://user-images.githubusercontent.com/270673/46908028-27c9b600-ceea-11e8-9b3d-200552dbd221.png)

**Comment by davidfowl** [comment]
It *might* be a timer issue. A dump would help.

**Comment by tbasallo** [comment]
Working on it. I'm watching this thing like a hawk and I have an alert to text me. 
I have these but it was at the tail end of a spike. Not too familiar on reading it so I think has nothing, but maybe it does.
[memory dumps on OneDrive](https://whitespacesdesign-my.sharepoint.com/:f:/g/personal/tony_whitespaces_design/EmmlM4KEY-JAp3--ZAKha9IB7XuUFbgBaz7bP4FepCfkxA?e=zQgpmR)

**Comment by davidfowl** [comment]
Are those profiles or memory dumps? How did you collect those?

**Comment by tbasallo** [comment]
Profiles, you're right.
Should I get them on the dotnet or w3wp?

**Comment by davidfowl** [comment]
dotnet

**Comment by tbasallo** [comment]
Will do. Thanks for your help on this.

**Comment by tbasallo** [comment]
Done. Since I disabled auto-scale it was easier to catch.

![image](https://user-images.githubusercontent.com/270673/46910011-a33b5f80-cf0a-11e8-8ccb-32732f32f492.png)

**Comment by davidfowl** [comment]
@tbasallo which one is it?

**Comment by tbasallo** [comment]
There are two apps, listed from most recent to oldest. I took a couple dumps of each of the apps

API ONLY, usually has the most usage 
- dotnet-b3164c-10-13-21-00-14.dmp
- dotnet-b3164c-10-13-20-51-52.dmp
- dotnet-b3164c-10-13-20-50-14.dmp

WEB, has had usage lately - 
- dotnet-b3164c-10-13-21-02-10.dmp
- dotnet-b3164c-10-13-20-54-15.dmp

**Comment by davidfowl** [comment]
@tbasallo if you can repro it more easily now, capturing a trace would be ideal. I'm looking at both the dumps and older traces to see if anything stands out.

**Comment by tbasallo** [comment]
I can't repro it, but it's more isolated. When the CPU spikes, it's just these two and not any other services - before it was a "maybe it's..."

Capture a trace how?

**Comment by davidfowl** [comment]
The profiles you captured before. The flame graph looks like this:

![image](https://user-images.githubusercontent.com/95136/46911188-f01e3680-cf08-11e8-9144-100475cba810.png)

One of those big blocks in 

module coreclr <<coreclr!McGenControlCallbackV2>>

![image](https://user-images.githubusercontent.com/95136/46911206-615de980-cf09-11e8-8358-7a91a78b4017.png)

The calls to table storage and httpclient calls look like some of the hotter paths.

**Comment by tbasallo** [comment]
External calls using HttpClient is the main use. Which is why I thought the HttpClientFactory was at fault. Adding table storage calls adds to the network usage.

Silly question: Could this be "normal" for the amount of network/http client usage?

**Comment by davidfowl** [comment]
So far nothing looks surprising. It just looks like CPU usage.

**Comment by tbasallo** [comment]
I just separated the web and API into their own plans. Trying to isolate if one or the other is causing the spikes that hold for so long. This is not an overly complicated app.

There's not that many requests coming in to spike to 100 and hold for 20 -30 minutes. There's gotta be something I'm missing.

**Comment by davidfowl** [comment]
Great, when you see it again, let me know. Collect a trace (profile) and a dump. We'll see if we can get to the bottom of it.

**Comment by tbasallo** [comment]
Definitely isolated to the API app. At 1:30PM today it spiked and hasn't gone down, 3.5 half hours later. Since I didn't allow for more instances to spin up, it's chugging along. I'm going otrestart the app now. I took 2 dumps and two traces, back to back. I tried taking a really long trace, but it timed out.

Someinfo: memory steady at 50%, 

[memory dumps on OneDrive ](https://whitespacesdesign-my.sharepoint.com/:f:/g/personal/tony_whitespaces_design/EmmlM4KEY-JAp3--ZAKha9IB7XuUFbgBaz7bP4FepCfkxA?e=zQgpmR)

![image](https://user-images.githubusercontent.com/270673/46922080-e8769480-cfd1-11e8-9aaf-defeb6b2ddcd.png)

**Comment by tbasallo** [comment]
For context, requests are very low:
![image](https://user-images.githubusercontent.com/270673/46922144-c598b000-cfd2-11e8-851b-ee1f51de270d.png)

**Comment by davidfowl** [comment]
@tbasallo looking at the profile, it seems there's an expensive LINQ query in `EstrellaInsurance.Api.Controllers.RaterV2Controller`. 

![image](https://user-images.githubusercontent.com/95136/46933256-2a223200-d008-11e8-8e4d-f4988d022b53.png)

It's taking up most of the time in the profile. You *might* be experiencing client side evaluation in your EF query, se https://docs.microsoft.com/en-us/ef/core/querying/client-eval in your EF query (if you're using EF).

**Comment by tbasallo** [comment]
Yeah, I thought that's what I saw when I tried looking at it with PerfView. But, I am not sure what that is. There's not very much LINQ in this project. There's no big collections.

This project does 3 things

- gets zipcode/county information (HTTPClient)
- validates an json object (various table storage and SQL calls - about 6 in total)
- gets VIN information (HTTPClient) as part of he above when needed

It was pegged at 100% for 4 hours with < 15 requests/s. It's cruising at 25% now and there's 0 requests (east coast service).

I'm so desperate that I started and I'm almost done changing it back to 4.7.2. I'm going to run one more full day against 2.1 today (Monday) and then I'll switch to 4.7 on Tuesday. That'll at least answer my nagging suspicion that this started with the move to 2.1. 

If it behaves "normal" on 4.7 then at least I know it's something on the 2.1 stack. Then I can focus on dependencies one by one.

**Comment by davidfowl** [comment]
This looks to be the expensive method:

![image](https://user-images.githubusercontent.com/95136/46933801-6191de00-d00a-11e8-9a3c-19535ac33cab.png)

Are you using EntityFramework?

**Comment by davidfowl** [comment]
The dump also shows one of the threads in this method:

```EstrellaInsurance.Api.dll!EstrellaInsurance.Api.Controllers.RaterV2Controller.AssignAgency(EstrellaInsurance.Quotes.v2Models.QuoteModel quote, EstrellaInsurance.DomainSettings domainSettings)```

**Comment by tbasallo** [comment]
No EF. I use NPoco - which has always performed like a champ (similar to dapper).

That call does 1 DB call and then 2 HTTP calls if there's no record in the DB. The object returned has 5 properties. And when I test them, they're fast (< 100ms).

I'll look at that again and see if I missed something.

**Comment by tbasallo** [comment]
So, after deploying a "classic" version of the same code (it's crazy how fast you can rebuild something once it's done :) ) for 4.7. It seems that they both exhibit the same pattern of small/medium spikes every 20 minutes.

Must be something that just happens. I'll keeping looking at it. Thanks @davidfowl for the extra set of eyes.

**Comment by davidfowl** [comment]
@tbasallo when you figure it out or if you get more data let me know. I'm interested in the resolution.
