### ISSUE TITLE
In the controller, how do I find the specified type client by name

### ISSUE THREAD

**Issue by blance1024** [aspnet/HttpClientFactory#193]
Multiple generic typed clients will only get last added HttpClient.（https://github.com/aspnet/HttpClientFactory/issues/151）
In the controller, how do I find the specified type client by name？

services.AddHttpClient《JsonForApi》("test",cfg =>
            {
                cfg.BaseAddress = new Uri("https://192.168.1.106");
            });

services.AddHttpClient《JsonForApi》("baidu", cfg =>
            {
                cfg.BaseAddress = new Uri("http://www.baidu.com");
            });

**Comment by blance1024** [comment]
services.AddHttpClient<JsonForApi<string>>(cfg =>
          {
              cfg.BaseAddress = new Uri("https://192.168.1.106");
          }
            )
            .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
            {
                //ServerCertificateCustomValidationCallback = JsonForApi.CustomCertificateValidationCallback
            });

            services.AddHttpClient<JsonForApi<string>>("baidu", cfg =>
            {
                cfg.BaseAddress = new Uri("http://www.baidu.com");
            });

**Comment by rynowak** [comment]
This is not supported, they need to be different types.

**Comment by natemcmaster** [comment]
Closing as it appears the question was answered. If you still need more help, please use the new repo for this project: https://github.com/aspnet/Extensions
