### ISSUE TITLE
Confusing DI behaviour

### ISSUE THREAD

**Issue by bjornsallarp** [aspnet/HttpClientFactory#195]
Hi! Just wasted more than an hour trying to figure out why on gods earth DI could not activate my very simple case. 

I want to inject a configured HttpClient into a specific class. This is supported and I've found tons of resources telling me this is supported. 

The problem was in which order I was calling AddHttpClient and registering the target class. I'm by no means an expert on Ioc containers but the order of registrations should not matter(?). Here's a short sample showing the problem:

```
    public class IocTest
    {
        public class MyClient
        {
            public MyClient(HttpClient client) { }
        }

        [Test]
        public void DoesntWork()
        {
            var services = new ServiceCollection();

            services.AddHttpClient<MyClient>();
            services.AddTransient<MyClient>();

            var provider = services.BuildServiceProvider();
            provider.GetRequiredService<MyClient>();
        }

        [Test]
        public void DoesWork()
        {
            var services = new ServiceCollection();

            services.AddTransient<MyClient>();
            services.AddHttpClient<MyClient>();

            var provider = services.BuildServiceProvider();
            provider.GetRequiredService<MyClient>();
        }
    }
```

Is this fixable? If not, could you drop an error message when AddHttpClient is called on something that isn't registered already and wont work? Perhaps look at the docs and clearly point this out.

Using these packages
```
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
<PackageReference Include="Microsoft.Extensions.Http" Version="2.1.1" />
```

**Comment by dferretti** [comment]
Order does matter when registering a service, and in this container the last registration wins when you are requesting a single service. So if you have 

    services.AddTransient<MyClient>(provider => ...);
    services.AddTransient<MyClient>(provider => ...);

then when you ask for MyClient, only the second factory will run. 
`services.AddHttpClient<MyClient>()` internally calls a few things, but it ends up with 

    services.AddTransient<MyClient>(provider => ... some IHttpClientFactory and ITypedHttpClientFactory calls)

so it will override (in the working case) your first AddTransient call with one that correctly adds the configured httpclient to your MyClient's constructor
In your non-working case, your AddTransient is overriding the HttpClientFactory's transient, so when it tries to instantiate your MyClient it will fail because HttpClient is not a service that was registered.

**Comment by bjornsallarp** [comment]
Thank you for the quick answer! I understand why this is happening and indeed I don't have to register my service, AddHttpClient does that behind the scenes. With Ninject and other containers I have experience with you can control which instance get injected into what. I thought AddHttpClient was doing just that. I can see now in [this documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_HttpClientFactoryServiceCollectionExtensions_AddHttpClient__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_), it clearly states what is going on.

Thank you for the quick feedback!
