### ISSUE TITLE
Remove MessageHandler - Logging Message Handler

### ISSUE THREAD

**Issue by stephenlautier** [aspnet/HttpClientFactory#196]
Is there a way to remove the default `LoggingHttpMessageHandler` or any other `MessageHandlers`?

e.g.

```cs
services.AddHttpClient("minos")
   .RemoveHttpMessageHandler<LoggingHttpMessageHandler>();
```

Basically we have our own custom logger middleware and ideally we would like to remove the default one. (i know we can filter loglevels for the namespace, but if its not even invoked would be nicer)

Thanks!

**Comment by rynowak** [comment]
Yes, you can do this by removing all services of type `IHttpMessageHandlerBuilderFilter`

`https://github.com/aspnet/HttpClientFactory/blob/0677ac9f1e3efeb7557291ed42c726c60bde9c93/src/Microsoft.Extensions.Http/IHttpMessageHandlerBuilderFilter.cs`

**Comment by stephenlautier** [comment]
but can I control which I can remove? because I don't want to remove all `MessageHandlers` just the logger. 

Also if you can provide a sample usage it would be really helpful

**Comment by rynowak** [comment]
Put this in `ConfigureServices` after where you register httpclient factory. This won't impact any of your registrations, but it will prevent us from adding our default logging. 

```
            foreach (var service in serviceCollection.Where(s => s.ServiceType == typeof(IHttpMessageHandlerFactory)))
            {
                serviceCollection.Remove(service);
            }
```

Do you have suggestions about how we could change/improve the existing logging? This has been asked a few times and always want to know if there is something you want more/less of or to be done differently

**Comment by stephenlautier** [comment]
Thanks for the code!

Basically I'm the author of [FluentlyHttpClient](https://github.com/sketch7/fluentlyhttpclient), which is a .NET Standard library with fluent api for httpclient, and I had middlewares (messagehandlers) implemented before this was out (which it is super good that they are out of the box btw, not complaining at all)

These are my logging/timer middleware if you want to get any ideas
- [LoggerMiddleware](https://github.com/sketch7/FluentlyHttpClient/blob/master/src/FluentlyHttpClient/Middleware/LoggerHttpMiddleware.cs) 
- [TimerMiddleware](https://github.com/sketch7/FluentlyHttpClient/blob/master/src/FluentlyHttpClient/Middleware/TimerHttpMiddleware.cs)

These are some points which might be nice, which I already have:
 - Ability to adjust a message handler options for each request (we find it super useful), this can be for any handler but for logging specifically this can enable detailed logging for request and/or response
 - For the timing - configuration for threshold (global + per requets), in order to log it as warning instead (requests take too long)
 - Include request info for timing (useful when checking logs) - `"in Ending processing HTTP request after..."` - when we see logs, we need to know which request (url/method) took long
 - Include request/response info such as statuscode/url in `"Received Http response after...`
 - Perhaps also round/format ms numbers to max 2 digits e.g. `2767.86ms` from `2767.8621ms`

The following is a simple sample with what I have (the highlighted are mine)

![image](https://user-images.githubusercontent.com/3908723/47243200-95e21180-d3f1-11e8-92f4-4598b082ab8b.png)

Hope you find something useful, and thanks again!

P.S. would be nice if there is an easier way for removing message handlers, such as `.RemoveHttpMessageHandler<LoggingHttpMessageHandler>()`  ☺️

**Comment by stephenlautier** [comment]
@rynowak I think you meant `IHttpMessageHandlerBuilderFilter` as your first post not `IHttpMessageHandlerFactory`.

A working solution and the simplest is the following:

```cs
services.RemoveAll<IHttpMessageHandlerBuilderFilter>();
```

Thanks for your help!
