### ISSUE TITLE
Cleanup timer captures logging scopes

### ISSUE THREAD

**Issue by cortex93** [aspnet/HttpClientFactory#199]
Hi,

I think that the cleanup timer somehow captures the state of logging scope stack (I used Serilog which uses AsyncLocal like the console logger I think)

I create scope early around request execution and certainly before my service is resolved and HttpClientFactory singleton is created for the first time.

When the timer ticks, call to Log in the method enumerates scopes created in the request.

Is the timer independent of any thread context or async locals ?

**Comment by martincostello** [comment]
I believe this is the same as #171, which is fixed for 2.2.0.

**Comment by cortex93** [comment]
You are right. In the meantime, is there any workaround for 2.1.0 we can do on our side ?
If not, could a fix be published ?

**Comment by martincostello** [comment]
Not that I'm aware of, and as 2.2.0 is so close to release it probably won't be patched to `2.1.x`.
