### ISSUE TITLE
Question - HttpMessageHandler access session

### ISSUE THREAD

**Issue by rajeshaz09** [aspnet/HttpClientFactory#201]
My web app talks to backed API server using authentication token that was stored in user session. Since authentication header need to be add to all API server calls, I am planning to implement using httpmessagehandler.
But HttpMessageHandlers lifetime is different. 

How to access current user's httpcontext or session in messagehandler?

**Comment by rynowak** [comment]
Use `IHttpContextAccessor` https://github.com/aspnet/HttpAbstractions/blob/d6a3c3f83e0abb54472f19103bf385ca9d8ead5f/src/Microsoft.AspNetCore.Http/HttpServiceCollectionExtensions.cs#L20

**Comment by natemcmaster** [comment]
Closing as it appears the question was answered. If you still need more help, please use the new repo for this project: https://github.com/aspnet/Extensions
