### ISSUE TITLE
Is it possible for HttpClientFactory to target .NET Standard?

### ISSUE THREAD

**Issue by danielkatz** [aspnet/HttpClientFactory#202]
Xamarin based clients have all the same issues of managing the lifecycles of HttpClient and its handler instances.
If HttpClientFactory could target .NET Standard, instead of .NET Core, it'll be very useful in the Xamarin eco-system as well.

**Comment by martincostello** [comment]
It does target .NET Standard:

https://github.com/aspnet/HttpClientFactory/blob/4dfcf7485e62819d0d73c00d7e7eb53d75abdbd3/src/Microsoft.Extensions.Http/Microsoft.Extensions.Http.csproj#L9
