### ISSUE TITLE
Invalid input argument check

### ISSUE THREAD

**Issue by StarLancer** [aspnet/HttpClientFactory#21]
https://github.com/aspnet/HttpClientFactory/blob/8a643346089ce2356ac4bcc07f217f256004a00d/src/Microsoft.Extensions.Http/DefaultHttpClientFactory.cs#L47

Is the space character a valid name?

**Comment by Eilon** [comment]
I would think any non-`null` string would be valid. I don't think the names themselves matter. For example, `h̠̰̲ͮ͠eͭ̏ͧ͠l̹͈̲̮̼͇̰ͨ͌̚͜l̵̩͔̒̂ͨo̶͎̥̬̬̠̭̙ͣ̆̾̑͊͋` should be a perfectly fine name as well.

cc @rynowak @glennc in case you have further thoughts.

**Comment by rynowak** [comment]
Yes, any non-null string is valid. These are programmatic identifiers. 

If it hurts when you do that, stop doing that 😆
