### ISSUE TITLE
Package availability?

### ISSUE THREAD

**Issue by NickDarvey** [aspnet/HttpClientFactory#34]
Hi,

I stumbled on this while looking for a HttpClient abstraction. `IHttpClientFactory` looks pretty good, but how can I grab this as a package to use this in my project? I can only find it [here](https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.Extensions.Http) but it would be great to be able to use this in my AspNetCore 2.0.1 project. If it's not available individually, is it part of some other package that is available for consumption?

Nick

**Comment by rynowak** [comment]
Hi @NickDarvey - the plan right now is to release this as part to 2.1.0 The current code builds against 2.1.0 versions of options and requires some of features that have been added recently.

I'd suggest building this from source as a stopgap (change the dependencies to 2.0.0 and see what breaks).
