### ISSUE TITLE
Docs wishlist

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#37]
Starting and issue to track items we will need to cover in does just so I can add notes and close out other issues.

--------

#### Using IHttpClientFactory outside of ASP.NET Core

We recommend using the DI container in your other app, even if it's just to bootstrap the factory.

#### Using IHttpClientFactory + Named Clients in tests

We recommend mocking the `IHttpClientClientFactory` rather than trying to configure it using DI. The contract is really simple to mock and usually requires new-ing up an `HttpClient`.

For the `HttpClient` itself, there are some good libraries already out there that support creating an `HttpMessageHandler` that will do what you want for the test. See https://github.com/aspnet/HttpClientFactory/issues/28#issuecomment-343800400 for some additional discussion. We should document some use cases to these libraries and point to them in our docs.

We want to try and avoid requiring DI in tests - that requires you to open pandora's box.

**Comment by glennc** [comment]
I've started filling in the Wiki with content that can later be turned into docs on the docs site.

**Comment by rynowak** [comment]
I'm closing this issue since I might almost everything we care about is already being captured in the docs, and that's tracked elsewhere.
