### ISSUE TITLE
Handling DNS TTLs?

### ISSUE THREAD

**Issue by martincostello** [aspnet/HttpClientFactory#44]
Having just read through [this (long) issue](https://github.com/dotnet/corefx/issues/11224) relating to `HttpClient` and DNS TTLs, there are comments made about pooling of clients/handlers so that over time cached IP addresses from DNS entries are evicted. If if understood correctly, pooling is something that's been at least mentioned in this repo, but I'm guessing probably from the socket-exhaustion point-of-view.

Is period flushing of shared instances from a DNS point-of-view something that's being explicitly considered as a use case for things that HTTP client factory would be able to do to help consumers fall into the pit of success for? If not, is it worth incorporating into the design?

**Comment by mkArtakMSFT** [comment]
@glennc, @rynowak any thoughts on this?

**Comment by bulfonjf** [comment]
How about this URL? https://github.com/NimaAra/Easy.Common/blob/master/Easy.Common/RestClient.cs

**Comment by glennc** [comment]
Hey @martincostello, our design for this today takes into account the DNS caching that the native handler does. We will recycle handlers periodically to make sure that the DNS entries aren't cached forever.

We are also working with some corefx folks on a managed handler that will hopefully resolve this issue for us, meaning that we don't have to worry about it when using that handler. I don't know that we will completely fix these issues, but we are aware of them and are taking it into account in our designs.

**Comment by martincostello** [comment]
@glennc Thanks for the information Glenn 👍

**Comment by glennc** [comment]
No problems.
