### ISSUE TITLE
Recommendations for how to use against multiple host/port combinations

### ISSUE THREAD

**Issue by roryprimrose** [aspnet/HttpClientFactory#57]
This is a question rather than an issue. I have asked this in several places but not been able to get a reliable answer. 

My usage of HttpClient is to test the health of HTTP endpoints. As such, I am making calls out to many host/port combinations. The set of endpoints I check should be considered "random". My understanding regarding the reuse of HttpClientHandler is that it is only of benefit when connecting to the same host/port so that the socket can be reused.

My questions are:

- Should I use any caching of HttpClient (HttpClientHandler) instances when connecting to an unknown/random set of host/port combinations? 
- How does the API of this factory abstract that away so it doesn't matter to the developer?

If the host/port combination is the point of uniqueness to HttpClientHandler, then shouldn't this factory use the base uri of the endpoint (that represents host/port) in the signature of ```IHttpClientFactory.Create``` instead of a name. As an example, I'm guessing that the following pseudocode (while valid against the compiler) is a completely incorrect usage:

```
var client = factory.Create("test");

client.Get("https://www.firsthost.com/");
client.Get("https://www.firsthost.com:4532/");
client.Get("https://www.someotherhost.com/");
```

If the purpose of the name parameter is to control a cache around the socket to the host/port, this api does not appear to do that.

I'd love to hear some feedback on this. I'm really keen to know if I'm correct in my thinking or whether there is something I need to understand better.

Cheers

**Comment by Tratcher** [comment]
If you are highly unlikely to re-connect to the same host within a 2 minute period then yes, caching will not help you and may actually get in the way.

Some possible caveats:
- Any HTTP requests through an HTTP proxy may share connections even if ultimately going to unique hosts. This is not true for HTTPS requests though.
- In theory different sites hosted on the same public IP can also share connections (e.g. *.azurewebsites.net, reverse proxies). .NET didn't do this, but I don't know if .NET Core's WinHttp or Curl implementations do this.

**Comment by roryprimrose** [comment]
Thanks for the response @Tratcher. Regarding point 2, the only way to manage that in code would be to resolve the IP and cache based on that instead of host. This is probably not something that would be worthwhile me doing because the likelihood of being able to actually reuse a connection would be very low.

**Comment by glennc** [comment]
Named clients aren't really about optimizing caching, they are more about giving you control over configuring different clients for different purposes. Right now people are mostly gravitating to the caching ability of the factory, but it is more about configuring clients, providing typed clients, and plugging together delegating handlers to do interesting things to outgoing requests. Managing instances of the HttpClientHandler is a workaround we do in the factory until we fix the need for them in corefx itself.

**Comment by glennc** [comment]
Closing this as the discussion appears to be over. Jump in if you want to ask more questions or drill in more.
