### ISSUE TITLE
Investigate: Are there other things besides BaseAddress and Request Headers we care about?

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#6]

**Comment by lecaillon** [comment]
Add the option to configure the `HttpMessageHandler` of a `HttpClient`. Example:
```c#
services.AddNamedClient("github", o =>
{
    o.BaseAddress = new Uri("https://api.github.com");
    o.MessageHandler = new HttpClientHandler { UseProxy = false, AutomaticDecompression = DecompressionMethods.GZip };
});
```

**Comment by rynowak** [comment]
> Add the option to configure the HttpMessageHandler of a HttpClient.

Yes, we will do this for sure. I want to also mention that we're expecting the work going on in [dotnet/corefx](https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Net.Http) to make some improvements to the new managed handler. In particular https://github.com/dotnet/corefx/issues/24257 is an issue for microservice environments 

I think all 4 of these are useful https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx#Anchor_3 - especially the timeout.

I'm working through a design right now that will allow you to have a list of `Action<HttpClient>` for fine-grained control of these things

**Comment by gulbanana** [comment]
How about options which can improve performance when using web apis? For example, disabling expect: 100-connnect and Nagle’s algorithm.

**Comment by rynowak** [comment]
> How about options which can improve performance when using web apis? For example, disabling expect: 100-connnect and Nagle’s algorithm.

This is a better topic of discussion for dotnet/CoreFx - we're not implementing HTTP in this repo - that goes on over there -> https://github.com/dotnet/corefx

**Comment by bruno-garcia** [comment]
What about an API like:

`services.AddNamedClient<GithubClient>(o =>
{
    o.BaseAddress = new Uri("https://api.github.com");
    o.MessageHandler = new HttpClientHandler { UseProxy = false, AutomaticDecompression = DecompressionMethods.GZip };
});`

Where T (GithubClient in the example above) is some marker interface or class defined by the consumer. The type would be resolved from the container so one could take dependencies in its constructor, etc.

**Comment by rynowak** [comment]
I like it 👍

**Comment by rynowak** [comment]
By the way we're starting with something like what @lecaillon suggested - feedback on the PR has been positive so far. Moving this into working and removing needs-design

**Comment by rynowak** [comment]
8a64334
