### ISSUE TITLE
Scope of Polly polices in relation to named HttpClient configurations 

### ISSUE THREAD

**Issue by reisenberger** [aspnet/HttpClientFactory#60]
Not so much an issue as drawing out the below implication, and noting it for consideration for documentation

### Scope of Polly polices in relation to named `HttpClient` configurations 

Ensuring circuit-breaker and bulkhead policies maintain consistent state while handlers and `HttpClient` instances are recycled underneath them, has suggested [they should be singleton per named `HttpClient` configuration on `HttpClientFactory`](https://github.com/aspnet/HttpClientFactory/pull/58#discussion_r168919618).

The stateful nature of circuit-breaker and bulkhead policies also has [intended functional consequences when sharing policies across call sites](https://stackoverflow.com/a/44467225/):

**Circuit-breaker:** Sharing a CircuitBreakerPolicy instance at multiple call sites causes those call sites to share circuit statistics and state, and thus to break in common.

This is intended: for example, using the same CircuitBreakerPolicy instance for all calls to (various endpoints on) `contoso.com` means any call you place to any endpoint on `contoso.com` can know if other calls have already detected that `contoso.com` is 'down' (and broken the circuit).

**Bulkhead:** Calls placed through the same BulkheadPoliy instance share the capacity of that bulkhead.

---

The corollary of this for `HttpClientFactory` is:

**Circuit-breaker:** Where a named `HttpClient` configuration on an `HttpClientFactory` uses a CircuitBreakerPolicy, that named `HttpClient` should be usage-scoped to calls to endpoints the user wishes to break in common.

This is a good fit for the examples @rynowak / @glennc have given for `HttpClientFactory`, with eg a named client configuration of "github" being used with a BaseUri "github.com" (with the implication calls through it will be to somewhere on github.com).
  

**Bulkhead:** Similarly, a named `HttpClient` configuration, if configured with a `BulkheadPolicy`, should be usage-scoped to calls the user wishes to share that bulkhead capacity.

**Comment by rynowak** [comment]
Thanks, this is a great answer to some of the questions I have. A few thoughts.

Our 'builder' methods that take a lambda will close over the policy in question when invoked, preventing the policy from being created multiple times.

When a developer wants to share a policy between multiple named handlers, it sounds like they can either write code like this:
```
var myPolicy = Policy....; // create a policy once

services.AddHttpClient("github").AddPolicy(myPolicy);
services.AddHttpClient("facebook").AddPolicy(myPolicy);
```

Or we could register the policy registry in services and provide convenience methods to attach policy handlers using policies from the registry.

----

The latter sounds like a grow up story for the former. There's been some discussion of integration with the policy registry in comments and I've added it to my checklist here https://github.com/aspnet/HttpClientFactory/issues/8

I think the extent of our integration with the registry would be to patternize registering the registry in services and accessing policies from it. It seems like a nice to have.

**Comment by reisenberger** [comment]
x-ref for anyone landing here: response to `PolicyRegistry` integration in [#8](https://github.com/aspnet/HttpClientFactory/issues/8#issuecomment-367743719)

**Comment by rynowak** [comment]
Closing this as the policy registry work is checked in
