### ISSUE TITLE
Execution-scoped data in the Polly-HttpClientFactory integration: enabling rich and correct telemetry, and CachePolicy

### ISSUE THREAD

**Issue by reisenberger** [aspnet/HttpClientFactory#62]
Polly Policy instances can be used across multiple call sites for [intended functional outcomes](https://github.com/aspnet/HttpClientFactory/issues/60#issue-298001498).  This is a good fit for named `HttpClient` configurations on `HttpClientFactory` with a `BaseUri` eg `api.contoso.com` indicating all calls will be to endpoints on `api.contoso.com`.

To complement re-use, Polly provides an execution-scoped [`Context`](https://github.com/App-vNext/Polly/blob/754a4a920900e1ae56d4fdae7cbdfd02bcb8cbd1/src/Polly.Shared/Context.cs) which travels with every execution. This:

(a) provides a [correlation id unique to each execution](https://github.com/App-vNext/Polly/blob/754a4a920900e1ae56d4fdae7cbdfd02bcb8cbd1/src/Polly.Shared/Context.cs#L47-L58), allowing logging and telemetry to correlate the events particular to a single execution;
  
(b) [distinguishes different call sites](https://github.com/App-vNext/Polly/blob/754a4a920900e1ae56d4fdae7cbdfd02bcb8cbd1/src/Polly.Shared/Context.cs#L40-L45) at which Policy instances may be being used, allowing logging and telemetry to correlate statistics particular to a single usage site/call path;

+ For instance, it is typical to use the same circuit-breaker instance for all endpoints on `api.contoso.com`, but when analysing failures, it can be very useful to extract that call path A tended to be healthy but call path B tended to require retries, break circuits, etc.   

(c) allows the functioning of `CachePolicy`.  With `CachePolicy`, one typically configures a single `CachePolicy` instance, then `Context` [supplies the key that the policy should use for caching items](https://github.com/App-vNext/Polly/wiki/Cache#default-cachekeystrategy-if-none-specified) on that particular call path.

The execution-scoped `Polly.Context` is already made available to policy delegate hooks (eg [`onRetry`](https://github.com/App-vNext/Polly/blob/2862be4f4db5fd2fe4a97e9c55faf4b49793e95d/src/Polly.Shared/Retry/RetrySyntaxAsync.cs#L142), [`onBreak`](https://github.com/App-vNext/Polly/blob/2862be4f4db5fd2fe4a97e9c55faf4b49793e95d/src/Polly.Shared/CircuitBreaker/CircuitBreakerSyntaxAsync.cs#L100) etc) and will also be available to forthcoming raw telemetry events.

---

Without HttpClientFactory doing anything around this, correlation ids (a) would be inconsistent in cases where multiple Polly policies are applied by layering DelegatingHandlers (each `PolicyHttpMessageHandler` layer would generate a fresh guid).  And features (b) and (c) would not be available.

#### Options for supporting `Polly.Context` in `PolicyHttpMessageHandler` 

[Here within `PolicyHttpMessageHandler`](https://github.com/aspnet/HttpClientFactory/blob/9b11dd0a31de94acbbfc9e7e06015bc73043f20a/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L32-L33) we could:

```csharp
Polly.Context pollyExecutionContext = request.Properties[PollyContext] ?? new Polly.Context(); // [1]
request.Properties[PollyContext] = pollyExecutionContext; // [2]  

return _policy.ExecuteAsync((context, token) => base.SendAsync(request, token), pollyExecutionContext, cancellationToken); // [3]
```

where:

```csharp
private static readonly string PollyContext = "PollyExecutionContext"; // [4]
```

[1] and [2] ensure when there is a chain of delegating handlers, they all use the same context, fixing (a) above.  [3] just despatches so that all Polly logging and telemetry has access to the Context.

If we changed [4] to:

```csharp
public static readonly string PollyContext = "PollyExecutionContext"; // [4b]
```

then users who desired, would have this usage:

```csharp
request.Properties[PolicyHttpMessageHandler.PollyContext] = new Polly.Context("MyUsageKey"); // [5] 
var response = client.DoWhateverAsync(request...); // (as usual)
```

This enables and fixes both use cases (b) and (c) above.

---

Stepping back: the issue here is that Polly users normally code the `fooPolicy.ExecuteAsync(...)` call directly, so can [pass in](https://github.com/App-vNext/Polly/blob/2862be4f4db5fd2fe4a97e9c55faf4b49793e95d/src/Polly.Shared/PolicyAsync.cs#L469)  a `Context`.  In the `HttpClientFactory` integration, that call is (necessarily) [within `PolicyHttpMessageHandler.cs`](https://github.com/aspnet/HttpClientFactory/blob/ad8554ace8957a371523dad8395a220d4aec3f26/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L33), so the user cannot directly pass in `Context`.

`HttpClient` being (presumably) not for modification, [`HttpRequestMessage.Properties`](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L113-L123) seems like the intended(?)/available place for attaching execution-scoped data.  

The extra line, [5], would not be necessary for ordinary usage.  It would be an available option, for those who wanted the richer telemetry or to use `CachePolicy`.   

---

Thoughts? Should this be part of the Polly-HttpClientFactory story? Are there any good alternatives?

**Comment by rynowak** [comment]
I think this seems reasonable. It's something I was wondering about myself. 

We might even go further than 4b and just define extension methods that do this in a nicer way.

**Comment by reisenberger** [comment]
>We might even go further than 4b and just define extension methods that do this in a nicer way.

Perfect! My concern around [5] was that while sthg like this was necessary, it wasn't as pretty as it could be, so if you have licence to add extension methods to wrap-and-hide [4b] / [5], even better.

**Comment by rynowak** [comment]
This is done. We did all of this stuff 👍
