### ISSUE TITLE
Flaky test: Factory_CleanupCycle_DisposesLiveHandler 

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#64]
This test is failing on travis occaisionally https://travis-ci.org/aspnet/HttpClientFactory/jobs/344818297

**Comment by Eilon** [comment]
@rynowak if this is failing only on Travis, should we move this to RC1? And then maybe give up because we'll move to dotnet-ci instead?

**Comment by rynowak** [comment]
This seems like it's actual flakiness, and not a travis-related issue.

**Comment by Eilon** [comment]
Got it. Will we have time this week to investigate? If not, we should move to rc1

**Comment by rynowak** [comment]
Nothing ever exists entirely alone. Everything is in relation to everything else.

**Comment by Eilon** [comment]
My mind is blown.

**Comment by theezak** [comment]
not sure if it is related, but I have seen a race condition between the scheduled clean up job and tear down.  ActiveHandlerTrackingEntry probably should stop the timer during tear down ?

**Comment by rynowak** [comment]
hmm interesting. I'll take a look at that.

Do you have any more data points about how you figured that out?

**Comment by theezak** [comment]
Just hit it on a unit test where the assert failed. I am not completely sure what is going on, I didn't spend enough time in it. But definitely smelled like a race condition with the timers still running for the ActiveHandlerTrackingEntry instances and the clean up job depending upon the queue count not shrinking. I haven't seen it since implementing dispose methods, but that doesn't say much for race conditions.

**Comment by rynowak** [comment]
> Just hit it on a unit test where the assert failed

What assert was this? were you just building the HttpClientFactory repo or was this your own code?

**Comment by rynowak** [comment]
Looking at this log:


The failure is coming from here: https://travis-ci.org/aspnet/HttpClientFactory/jobs/358248760

https://github.com/aspnet/HttpClientFactory/blob/df30496fd89e6895cde4e9ae9953492ffe893000/test/Microsoft.Extensions.Http.Test/DefaultHttpClientFactoryTest.cs#L350

This means that the entry isn't eligible for GC, which means that the 'dummy' handler is still live. Since we're effectively relying on an implementation detail of the GC, I'm not 100% sure what we can do to improve the resilience of the test other than dumb things like retries.

I also realize that I'm not triggering a GC after waiting for finalizers. If a finalizer caused ressurection of the dummy handler these tests wouldn't handle it. I'm going to tweak things again and see if that makes it more reliable.

**Comment by rynowak** [comment]
@theezak - after looking at this test failure a bit more, I don't think the problem you're seeing is the one I've been looking at. If you can tell me what's going wrong for you, or provide a failing unit test, I can take a look at it.

**Comment by theezak** [comment]
Hi, 

That makes sense. I was looking (right or wrong) for a guarantee that on teardown the handlers are all disposed. handlers being disposed is completely dependent upon timers and GC timing.

For example: the following tests are near identical except for GC timing. One passes, one fails.

`        internal class TypedClient : IDisposable
        {
            public HttpClient Client { get; private set; }
            public TypedClient(HttpClient client) => Client = client;

            public void Dispose()
            {
                Client?.Dispose();
                Client = null;
            }
        }

        internal class Wrapper : HttpClientHandler
        {
            public Wrapper()
            {

            }

            internal Action NotifyDisposal;
            protected override void Dispose(bool disposing)
            {
                NotifyDisposal();
                base.Dispose(disposing);
            }
        }
        [TestMethod]
        public async Task TearDownDisposed()
        {
            var services = new ServiceCollection();
            var disposedHandler = false;
            services.AddHttpClient<TypedClient>().SetHandlerLifetime(new TimeSpan(0, 0, 0, 10)).ConfigurePrimaryHttpMessageHandler(() => new Wrapper
            {
                NotifyDisposal = () => disposedHandler = true
            });
            var provider = services.BuildServiceProvider();
            var factory = provider.GetRequiredService<System.Net.Http.IHttpClientFactory>();
            using (var scope = provider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                scope.ServiceProvider.GetRequiredService<TypedClient>();
            }
            await Task.Delay(15000);
            GC.Collect();
            await Task.Delay(15000);
            provider.Dispose();
            GC.Collect();
            Assert.AreEqual(true, disposedHandler);
        }

        [TestMethod]
        public async Task TearDownNotDisposed()
        {
            var services = new ServiceCollection();
            var disposedHandler = false;
            services.AddHttpClient<TypedClient>().SetHandlerLifetime(new TimeSpan(0, 0, 0, 10)).ConfigurePrimaryHttpMessageHandler(() => new Wrapper
            {
                NotifyDisposal = () => disposedHandler = true
            });
            var provider = services.BuildServiceProvider();
            var factory = provider.GetRequiredService<System.Net.Http.IHttpClientFactory>();
            using (var scope = provider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                scope.ServiceProvider.GetRequiredService<TypedClient>();
            }
            await Task.Delay(30000);
            provider.Dispose();
            GC.Collect();
            Assert.AreEqual(true, disposedHandler);
        }
    }`

**Comment by Eilon** [comment]
Moved to RC1.

**Comment by Eilon** [comment]
@rynowak - any further ideas on this flaky test?

**Comment by rynowak** [comment]
The handler isn't being GCed in the test. Dunno why.

**Comment by Eilon** [comment]
So we think it's a test-only issue? Or possibly a product issue?

**Comment by rynowak** [comment]
test issue. We're expecting the GC to have collected something and it hasn't

**Comment by Eilon** [comment]
OK, then MQ it is.

**Comment by rynowak** [comment]
This is done

**Comment by rynowak** [comment]
This is sadly not fixed, fails somewhat consistently still in debug on linux.

**Comment by rynowak** [comment]
I think this is actually fixed by my recent change. I'll wait to see it fixed in the official build before closing.

**Comment by rynowak** [comment]
Closing this because it seems fixed
