### ISSUE TITLE
Is there any chance to introduce IHttpClient form factory?

### ISSUE THREAD

**Issue by ptrstpp950** [aspnet/HttpClientFactory#67]
I know it is late for such thing, but it is probably the last chance to introduce `IHttpClient` interface.
If you introduce factory in 2.1 without interface it will always return a class. An interface is better for testing, mocking, etc. I'm sure that I don't have to prove this 🤓 

I can implement this if you only agree 😄

**Comment by DamianEdwards** [comment]
@glennc @davidfowl @rynowak

**Comment by Kralizek** [comment]
@ptrstpp950 Isn't better to have a mock of IHttpClientFactory that returns an HttpClient with a testing HttpMessageHandler? so that you receive a properly valued HttpResponseMessage instead of an empty shell.

**Comment by ptrstpp950** [comment]
@Kralizek I can easily provide implementation of IHttpClient with HttpResponseMessage if needed, but I agree that IHttpClientFactory will be useful also

**Comment by martincostello** [comment]
I’ve seen this discussed previously for the full framework. If memory serves, concrete types are preferred in this case because they’re easier to extend in future versions as extending an interface requires breaking changes from a binary compatibility point of view.

**Comment by AdamDotNet** [comment]
Is it sufficient that you can create an interface based custom/named HttpClient class? Seems a little easier to mock GetFoo() than the actual HTTP stuff going to actually do the GET /Foo?bar=true stuff on a theoretically IHttpClient, especially when you consider all the nice, automatic content negotiation of WebApi client package are all extension methods ultimately wrapping over the HttpClient's GetAsync method that just returns a byte array/stream.

**Comment by ptrstpp950** [comment]
But the HttpMessageHandler (base class for HttpClient) contains only one method (ok 3 in real but I don't count two Dispose). Mocking it is impossible because it looks like:
```
protected internal abstract Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken);
```

I fully agree with @AdamDotNet and I prefer to mock `GetFoo()`. But sometime it is not my choice and I have to "mock" response to create integration test using TestServer. To be fair probably changing above method from internal to `public` and allowing to inject my implementation of HttpMessageHandler to HttpClientFactory will be even better than the interface.

**Comment by davidfowl** [comment]
We have no plans to introduce an abstraction over HttpClient. See this for an uber long discussion on adding an interface for the client https://github.com/dotnet/corefx/issues/1624.

**Comment by glennc** [comment]
If you use the typed client pattern then the majority of your business logic would only be operating against your own typed client, which can have an interface. We have an overload of AddHttpClient that accepts an interface and a type for exactly that purpose. So the code that actually has to interact with HttpClient is the code that is deserializing return types and possibly some error handling and caching.

It is far from what you have to do today. For example, I wrote this to test my PageModel:

```csharp
[Fact]
public async Task GET_populates_values()
{
    IEnumerable<string> testValues = new List<string>() { "value1", "value2", "value3" };

    var valueService = new Mock<ValuesService>();
    valueService.Setup(x => x.GetValues()).Returns(Task.FromResult(testValues));

    var indexUnderTest = new IndexModel(valueService.Object);

    await indexUnderTest.OnGet();

    Assert.Equal(testValues, indexUnderTest.Values);
}
```

And when testing the ValuesService itself I mocked HttpMessageHandler without much problem:

```csharp
[Fact]
public async Task will_return_last_known_good()
{
    var firstCall = true;
    var handler = new MockMessageHandler(req =>
    {
        if(firstCall)
        {
            firstCall = false;
            var resp = new HttpResponseMessage(HttpStatusCode.OK);
            resp.Content = new StringContent("[\"testval\"]");
            return resp;
        }
        return new HttpResponseMessage(HttpStatusCode.InternalServerError);
    });

    var client = new HttpClient(handler);
    client.BaseAddress = new Uri("http://test.local");
    var cache = new MemoryCache(Options.Create(new MemoryCacheOptions()));

    var service = new ValuesService(client, cache, _logger.Object);

    await service.GetValues();
    var values = await service.GetValues();

    Assert.False(firstCall);
    Assert.Equal("testval", values.First());
}

public class MockMessageHandler : HttpMessageHandler
{
    private Func<HttpRequestMessage, HttpResponseMessage> _handler;

    public MockMessageHandler(Func<HttpRequestMessage, HttpResponseMessage> handler)
    {
        _handler = handler;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        return Task.FromResult(_handler(request));
    }
}
```

I didn't really feel the need for mocking HttpClient itself in any of that testing. The typed client abstraction made the tests that actually interacted with the HTTP types fairly small. Am I alone or naive in that?
