### ISSUE TITLE
Bug in HttpClientFactorySample RetryHandler causes no time between retries

### ISSUE THREAD

**Issue by skleanthous** [aspnet/HttpClientFactory#69]
### Title
In the `RetryHandler` class, in the `SendAsync` method, when an exception occurs, a call to `Task.Delay` is made but the result is never used/awaited.

### Functional impact
The sample code of RetryHandler will not wait for retries on error, instead it will instantly retry.

### Further technical details
See code here: https://github.com/aspnet/HttpClientFactory/blob/dev/samples/HttpClientFactorySample/Program.cs#L108

**Comment by skleanthous** [comment]
More than eager to create a PR to fix this :)

**Comment by Tratcher** [comment]
Go right ahead. We'll get the CLA sorted out.

**Comment by rynowak** [comment]
Thanks!
