### ISSUE TITLE
Question: How to use HttpClientHandler with IHttpClientFactory

### ISSUE THREAD

**Issue by evertmulder** [aspnet/HttpClientFactory#71]
A question on how to use the IHttpClientFactory. I would like to use a named client, but with a HttpClientHandler.

This how I used to create a HttpClient
```C#
var handler = new HttpClientHandler
{
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip
...
};
_httpClient = new HttpClient(handler);
```

But I would like to use the IHttpClientFactory like this:

startup.cs
```C# 
services.AddHttpClient("named", c =>
{
    c.BaseAddress = new Uri("TODO");
    c.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    c.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue
    {
        NoCache = true,
        NoStore = true,
        MaxAge = new TimeSpan(0),
        MustRevalidate = true
    };
});
```

How can I pass the HttpClientHandler to the named HttpClient. I was not able to find this. Any hints on how to achieve this?

**Comment by martincostello** [comment]
Looks like you call `ConfigurePrimaryHttpMessageHandler()` as part of using the HttpClient builders:

https://github.com/aspnet/HttpClientFactory/blob/4d976f65444766ac838b2c10be9b37024421f430/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L140

**Comment by rynowak** [comment]
Yes, @martincostello is right. You can configure the primary handler used by the factory for each named client this way.

**Comment by evertmulder** [comment]
@martincostello @rynowak Thanks a lot for pointing me in the right direction. I will test this tomorrow, but the following should do the trick. 

```C#
            services.AddHttpClient("named", c =>
            {
                c.BaseAddress = new Uri("TODO");
                c.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                c.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue
                {
                    NoCache = true,
                    NoStore = true,
                    MaxAge = new TimeSpan(0),
                    MustRevalidate = true
                };
            }).ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
            {
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            });
```

**Comment by rynowak** [comment]
Great! glad we could help

**Comment by Timovzl** [comment]
What if the handler must specify client certificates that are determined at runtime?

**Comment by davidfowl** [comment]
What’s the complication there?

**Comment by Timovzl** [comment]
@davidfowl To clarify, I see the HttpClientHandler being created at configuration time. At this point in the application (startup), we do not have the necessary information.

Each time we want to use the HttpClient, we load a certificate (perhaps based on a fingerprint), with the intention of getting an HttpClientHandler that uses that particular certificate. How can we achieve this?

**Comment by fleed** [comment]
@Timovzl I'm facing the same problem. I was expecting an overload of the `AddHttpClient` method providing the `IServiceProvider` instance, as it is in other circumstances.
Did you find an alternative solution?

**Comment by rynowak** [comment]
Please open a new issue rather than commenting on a closed issue.
