### ISSUE TITLE
Incorrect code sample in Wiki

### ISSUE THREAD

**Issue by martincostello** [aspnet/HttpClientFactory#74]
Reading through the [Consumption Patterns](https://github.com/aspnet/HttpClientFactory/wiki/Consumption-Patterns#registration-3) Wiki page for how to use Refit has the following line of example code:

```csharp
.AddTypedClient(c => Refit.RestService.For<IGitHubApi>());
```

This is incorrect as it does not pass the `HttpClient` (the `c` parameter in the lambda) to `For<T>()`.

It should be:

```csharp
.AddTypedClient(c => Refit.RestService.For<IGitHubApi>(c));
```

**Comment by rynowak** [comment]
Thanks for pointing this out! I've corrected this.
