### ISSUE TITLE
Add overloads with IServiceProvider to extension methods?

### ISSUE THREAD

**Issue by martincostello** [aspnet/HttpClientFactory#75]
As part of preliminary investigation of how to update the documentation and samples for `JustEat.HttpClientInterception` for ASP.NET Core 2.1 and HttpClientFactory (see justeat/httpclient-interception#23), I found that there was a lack of overloads on some extension method types that provided a ```IServiceProvider``` for some scenarios.

While not the end of the world in this particular example, I think this might be more of an issue in an application where settings from strongly-typed configuration (i.e. `Options<T>` things) are wanted by the consuming app to augment the HTTP client builder.

Is there merit in adding overloads similar to the following to allow for such usage patterns?

```csharp
// HttpClientBuilderExtensions
public static IHttpClientBuilder ConfigureHttpClient(this IHttpClientBuilder builder, Action<HttpClient, IServiceProvider> configureClient);

// HttpClientFactoryServiceCollectionExtensions
public static IHttpClientBuilder AddHttpClient(this IServiceCollection services, string name, Action<HttpClient, IServiceProvider> configureClient);
```

This question might be more of a question of discoverability, rather than missing functionality, and I'm just looking at things wrong. For example, I later found an overload to `AddTypedClient()` I missed initially, which lead to another refactor ([commit](https://github.com/justeat/httpclient-interception/pull/23/commits/a76c5edd33e20f315ef2d22aa313266ae88a969e)).

**Comment by martincostello** [comment]
Just as an update to the above, eventually I found `IHttpMessageHandlerBuilderFilter` which let me configure the handler order exactly as I wanted for the test setup, and now the implementation for setting up GitHub using this library in both our sample application and its tests is very neat. 👍

**Comment by rynowak** [comment]
Hi sorry for the delay in getting to this, I was out for a few days...

We didn't do this because you're typically in startup code at this point, and you have access to configuration directly.  Looking through your code sample, I now see what you're talking about.

Is the conclusion here that you still think we should add something like those extensions?

**Comment by martincostello** [comment]
I think so, as otherwise if you want to use other services to inform your HTTP registrations, I think you'd have to jump through a few hoops to carry a reference to the service collection yourself so you can turn it into a service provider and reference them at the point of activation.

Maybe it's an advanced scenario and over-complicates things for a first release? I mean, I eventually got to what I needed to do for my use-case, but it took a fair bit of digging around in the APIs to get it plumbed in.

**Comment by rynowak** [comment]
Ok cool beans, I'll take a crack at this later

**Comment by rynowak** [comment]
PR out for this, let me know what you think https://github.com/aspnet/HttpClientFactory/pull/82

**Comment by rynowak** [comment]
3978e61
