### ISSUE TITLE
Make HttpClientFactory work well without DI

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpClientFactory#9]

**Comment by glennc** [comment]
@anurse presumably HealthChecks requires the same thing and probably should do the same thing this does unless there are good reasons not to.

**Comment by anurse** [comment]
Yep, they'll need some love in that department

**Comment by davidfowl** [comment]
Why?

**Comment by anurse** [comment]
For HealthChecks, since it's going to ship for ASP.NET 4.x (when it does ship), it'll need some kind of build API for that because right now all it has is a constructor that takes an `IEnumerable<IHealthCheck>`, which is non-trivial to use.

**Comment by davidfowl** [comment]
I get healthchecks, I don't get this why this component needs to be designed for that.

**Comment by rynowak** [comment]
We've already had lotsa people tell us they want to use this in System.Web apps.

**Comment by rynowak** [comment]
For now our plan is require DI to use the factory. We'll encourage non-ASP.NET Core apps to use the DI system for now (3 lines of code).
